SET ECHO ON
SET DEFINE OFF
SET SERVEROUTPUT ON
WHENEVER SQLERROR CONTINUE ROLLBACK

DECLARE

BEGIN

	BEGIN
		Insert into ESB_CONSUMER (ID,SYSCODE,COUNTRY_ID,ENT_CODE,RCD_STATUS) values (ESB_CONSUMER_SEQ.NEXTVAL, (SELECT ID FROM ESB_SYSTEM WHERE CODE = 'FRW') ,
																					(SELECT ID FROM ESB_COUNTRY WHERE CODE = 'CHL'), 
																					(SELECT ID FROM ESB_ENTERPRISE WHERE CODE = 'ENTEL'), '1');
	END;
	
	BEGIN
		Insert into ESB_CONSUMER (ID,SYSCODE,COUNTRY_ID,ENT_CODE,RCD_STATUS) values (ESB_CONSUMER_SEQ.NEXTVAL, (SELECT ID FROM ESB_SYSTEM WHERE CODE = 'FRW') ,
																					(SELECT ID FROM ESB_COUNTRY WHERE CODE = 'PER'), 
																					(SELECT ID FROM ESB_ENTERPRISE WHERE CODE = 'ENTEL'), '1');
	END;
	
	
END;
/

COMMIT;
