SET ECHO ON
SET DEFINE OFF
SET SERVEROUTPUT ON
WHENEVER SQLERROR CONTINUE ROLLBACK

DECLARE

BEGIN

	BEGIN
		Insert into ESB_DEFAULT_CHECK (ID,TYPE,NAME,GRADE,RCD_STATUS,ELAPSED_TIME) values (ESB_DEFAULT_CHECK_SEQ.NEXTVAL,'1','ONGOING','100','1','0 0:1:0.0');
	END;
	
	BEGIN
		Insert into ESB_DEFAULT_CHECK (ID,TYPE,NAME,GRADE,RCD_STATUS,ELAPSED_TIME) values (ESB_DEFAULT_CHECK_SEQ.NEXTVAL,'2','REJECT','0','1','0 0:0:0.0');
	END;
	
END;
/

COMMIT;
