SET ECHO ON
SET DEFINE OFF
SET SERVEROUTPUT ON
WHENEVER SQLERROR CONTINUE ROLLBACK

DECLARE

BEGIN

	BEGIN
		INSERT INTO ESB_SERVICE_DETAILS_TYPE (ID, NAME, DESCRIPTION, RCD_STATUS) VALUES (ESB_SERVICES_DETAILS_TYPE_SEQ.NEXTVAL, 'Endpoint', 'Url Endpoint of service', 1);
	END;
	
END;
/

COMMIT;
