SET ECHO ON
SET DEFINE OFF
SET SERVEROUTPUT ON
WHENEVER SQLERROR CONTINUE ROLLBACK

DECLARE

BEGIN

	BEGIN
		Insert into ESB_SEVERITY (ID,"LEVEL",DESCRIPTION,"ORDER",RCD_STATUS) values (ESB_SEVERITY_SEQ.NEXTVAL,'INFO','Log Info level','100','0');
	END;

	BEGIN
		Insert into ESB_SEVERITY (ID,"LEVEL",DESCRIPTION,"ORDER",RCD_STATUS) values (ESB_SEVERITY_SEQ.NEXTVAL,'WARNING','Log Warning level','200','0');
	END;
	
	BEGIN
		Insert into ESB_SEVERITY (ID,"LEVEL",DESCRIPTION,"ORDER",RCD_STATUS) values (ESB_SEVERITY_SEQ.NEXTVAL,'DEBUG','Log Debug level','0','0');
	END;
	
END;
/

COMMIT;


