SET ECHO ON
SET DEFINE OFF
SET SERVEROUTPUT ON
WHENEVER SQLERROR CONTINUE ROLLBACK

DECLARE

BEGIN

	BEGIN	
		INSERT INTO ESB_CAPABILITY_DETAILS_TYPE (ID, NAME, DESCRIPTION, RCD_STATUS) VALUES (ESB_CAP_DETAILS_TYPE_SEQ.NEXTVAL, 'Action', 'SOAP Action', 1);
	END;
	
END;
/

COMMIT;
