SET ECHO ON
SET DEFINE OFF
SET SERVEROUTPUT ON
WHENEVER SQLERROR CONTINUE ROLLBACK

DECLARE

BEGIN

	BEGIN
		INSERT INTO ESB_ERROR_TREATMENT_TYPE (ID, NAME, DESCRIPTION, RCD_STATUS) VALUES (1, 'Mail', 'Envio de Mail', 1);
	END;
	
	BEGIN
		INSERT INTO ESB_ERROR_TREATMENT_TYPE (ID, NAME, DESCRIPTION, RCD_STATUS) VALUES (2, 'Retry', 'Reintento de una capacidad', 1);
	END;
END;
/

COMMIT;

