SET ECHO ON
SET DEFINE OFF
SET SERVEROUTPUT ON
WHENEVER SQLERROR CONTINUE ROLLBACK

DECLARE

BEGIN

	BEGIN
		Insert into ESB_CORRELATION_MEMBER_TYPE (ID,NAME,DESCRIPTION) values (ESB_CORRELATION_MEMBER_T_SEQ.NEXTVAL,'GroupOwner','Creador del Grupo.');
	END;
	
	BEGIN
		Insert into ESB_CORRELATION_MEMBER_TYPE (ID,NAME,DESCRIPTION) values (ESB_CORRELATION_MEMBER_T_SEQ.NEXTVAL,'GroupController','Controlador del Grupo.');
	END;
	
	BEGIN
		Insert into ESB_CORRELATION_MEMBER_TYPE (ID,NAME,DESCRIPTION) values (ESB_CORRELATION_MEMBER_T_SEQ.NEXTVAL,'GroupProvider','Proveedor del Grupo.');
	END;
	
	BEGIN
		Insert into ESB_CORRELATION_MEMBER_TYPE (ID,NAME,DESCRIPTION) values (ESB_CORRELATION_MEMBER_T_SEQ.NEXTVAL,'GroupConsumer','Consumidor del Grupo.');
	END;

END;
/

COMMIT;
