SET ECHO ON
SET DEFINE OFF
SET SERVEROUTPUT ON
WHENEVER SQLERROR CONTINUE ROLLBACK

DECLARE

BEGIN

	BEGIN
		Insert into ESB_ENTERPRISE (ID,CODE,NAME,RCD_STATUS) values (ESB_ENTERPRISE_SEQ.NEXTVAL,'ENTEL','ENTEL','0');
	END;
	
	BEGIN
		INSERT INTO ESB_ENTERPRISE   (ID,CODE,NAME,RCD_STATUS)  VALUES  (ESB_ENTERPRISE_SEQ.NEXTVAL,'250','250','1' );
	END;
	
	

END;

/

COMMIT;
