SET ECHO ON
SET DEFINE OFF
SET SERVEROUTPUT ON
WHENEVER SQLERROR CONTINUE ROLLBACK

DECLARE

BEGIN

	BEGIN
		Insert into ESB_CONSUMER_DETAILS_TYPE (ID,NAME,DESCRIPTION) values (ESB_CONSUMER_DETAILS_TYPE_SEQ.NEXTVAL,'TRANSPORT','Consumer Callback TRANSPORT');
	END;
	
	BEGIN		
		Insert into ESB_CONSUMER_DETAILS_TYPE (ID,NAME,DESCRIPTION) values (ESB_CONSUMER_DETAILS_TYPE_SEQ.NEXTVAL,'URL','Consumer Callback URI');
	END;
	
	BEGIN		
		Insert into ESB_CONSUMER_DETAILS_TYPE (ID,NAME,DESCRIPTION) values (ESB_CONSUMER_DETAILS_TYPE_SEQ.NEXTVAL,'Mail','Mail Address');
	END;

END;
/

COMMIT;
