SET ECHO ONSET DEFINE OFFSET SERVEROUTPUT ONWHENEVER SQLERROR CONTINUE ROLLBACKDECLAREvRes NUMBER;BEGIN
	BEGIN			INSERT INTO ESB_ERROR_STATUS_TYPE(ID,NAME,DESCRIPTION,RCD_STATUS) values ( ESB_ERROR_STATUS_TYPE_SEQ.NEXTVAL,'OK','Transaccion que finaliza exitosamente.','1');	END;
	BEGIN			INSERT INTO ESB_ERROR_STATUS_TYPE(ID,NAME,DESCRIPTION,RCD_STATUS) values ( ESB_ERROR_STATUS_TYPE_SEQ.NEXTVAL,'WARNING','Transaccion que finaliza con advertencias','1');	END;
	BEGIN			INSERT INTO ESB_ERROR_STATUS_TYPE(ID,NAME,DESCRIPTION,RCD_STATUS) values ( ESB_ERROR_STATUS_TYPE_SEQ.NEXTVAL,'ERROR','Transaccion que finaliza con error','1');	END;
END;/COMMIT;
