SET ECHO ON
SET DEFINE OFF
SET SERVEROUTPUT ON
WHENEVER SQLERROR CONTINUE ROLLBACK

DECLARE

BEGIN

	BEGIN
		Insert into ESB_ENDPOINT_TRANSPORT (ID,NAME,RCD_STATUS) values (ESB_ENDPOINT_TRANSPORT_SEQ.NEXTVAL,'MQ','1');
	END;
	
	BEGIN
		Insert into ESB_ENDPOINT_TRANSPORT (ID,NAME,RCD_STATUS) values (ESB_ENDPOINT_TRANSPORT_SEQ.NEXTVAL,'OSB','1');
	END;
	
	BEGIN
		Insert into ESB_ENDPOINT_TRANSPORT (ID,NAME,RCD_STATUS) values (ESB_ENDPOINT_TRANSPORT_SEQ.NEXTVAL,'JNDI','1');
	END;
	
	BEGIN
		Insert into ESB_ENDPOINT_TRANSPORT (ID,NAME,RCD_STATUS) values (ESB_ENDPOINT_TRANSPORT_SEQ.NEXTVAL,'JMS','1');
	END;
	
	BEGIN
		Insert into ESB_ENDPOINT_TRANSPORT (ID,NAME,RCD_STATUS) values (ESB_ENDPOINT_TRANSPORT_SEQ.NEXTVAL,'HTTP','1');
	END;
		
	BEGIN	
		Insert into ESB_ENDPOINT_TRANSPORT (ID,NAME,RCD_STATUS) values (ESB_ENDPOINT_TRANSPORT_SEQ.NEXTVAL,'HTTPSOAP12','1');
	END;
	
	BEGIN	
		Insert into ESB_ENDPOINT_TRANSPORT (ID,NAME,RCD_STATUS) values (ESB_ENDPOINT_TRANSPORT_SEQ.NEXTVAL,'HTTPJSON','1');
	END;
	
	BEGIN
		Insert into ESB_ENDPOINT_TRANSPORT (ID,NAME,RCD_STATUS) values (ESB_ENDPOINT_TRANSPORT_SEQ.NEXTVAL,'HTTPSOAP11','1');
	END;

END;
/

COMMIT;

