SET ECHO ON
SET DEFINE OFF
SET SERVEROUTPUT ON
WHENEVER SQLERROR CONTINUE ROLLBACK

DECLARE

BEGIN

	BEGIN
		Insert into ESB_CHECK_TYPE (ID,NAME,GRADE,RCD_STATUS) values (ESB_CHECK_TYPE_SEQ.NEXTVAL,'IDEMPOTENT','10','1');
	END;
	
	BEGIN
		Insert into ESB_CHECK_TYPE (ID,NAME,GRADE,RCD_STATUS) values (ESB_CHECK_TYPE_SEQ.NEXTVAL,'RESULT','5','1');
	END;

END;
/

COMMIT;
