SET ECHO ON
SET DEFINE OFF
SET SERVEROUTPUT ON
WHENEVER SQLERROR CONTINUE ROLLBACK

DECLARE

BEGIN

	BEGIN
		Insert into ESB_COUNTRY (ID,CODE,NAME,DESCRIPTION,RCD_STATUS) values (ESB_COUNTRY_SEQ.NEXTVAL,'0','UNK','UNKNOWN','1');
	END;
	
	BEGIN
		Insert into ESB_COUNTRY (ID,CODE,NAME,DESCRIPTION,RCD_STATUS) values (ESB_COUNTRY_SEQ.NEXTVAL,'CHL','CHL','CHILE','1');
	END;
	
	BEGIN
		Insert into ESB_COUNTRY (ID,CODE,NAME,DESCRIPTION,RCD_STATUS) values (ESB_COUNTRY_SEQ.NEXTVAL,'PER','PER','PERU','1' );
	END;
	
	
	
	
	


END;
/

COMMIT;
