<wsdl:definitions targetNamespace="http://www.entel.cl/RA/INT-SIE-EAI/getMarketingCampaign/v1" xmlns:tns="http://www.entel.cl/RA/INT-SIE-EAI/getMarketingCampaign/v1" xmlns:xs="http://www.w3.org/2001/XMLSchema" xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/" xmlns:wsoap12="http://schemas.xmlsoap.org/wsdl/soap12/" xmlns:ns="http://schemas.xmlsoap.org/soap/encoding/" xmlns:csmns="http://www.entel.cl/CSM/RA/INT-SIE-EAI/getMarketingCampaign/v1">
  <wsdl:types>
    <xs:schema xmlns:xsd="http://www.w3.org/2001/XMLSchema">
      <xs:import namespace="http://www.entel.cl/CSM/RA/INT-SIE-EAI/getMarketingCampaign/v1"
                 schemaLocation="INT-SIE-EAI_getMarketingCampaign_v1_CSM.xsd"/>
    </xs:schema>
  </wsdl:types>

  <wsdl:message name="getMarketingCampaign_Message_In">
    <wsdl:part name="In" element="csmns:INT-SIE-EAI_getMarketingCampaign_REQ"/>
  </wsdl:message>
  
  <wsdl:message name="getMarketingCampaign_Message_Out">
    <wsdl:part name="Out" element="csmns:INT-SIE-EAI_getMarketingCampaign_RSP"/>
  </wsdl:message>
  
 
  <wsdl:portType name="getMarketingCampaign_PortType">
    <wsdl:operation name="getMarketingCampaign">
      <wsdl:input message="tns:getMarketingCampaign_Message_In"/>
      <wsdl:output message="tns:getMarketingCampaign_Message_Out"/>
    </wsdl:operation>
  </wsdl:portType>

  
  <wsdl:binding name="getMarketingCampaign_SOAP12Binding" type="tns:getMarketingCampaign_PortType">
    <wsoap12:binding style="document" transport="http://www.bea.com/wli/sb/transports/sb"/>
    <wsdl:operation name="getMarketingCampaign">
      <wsoap12:operation style="document" soapAction=""/>
      <wsdl:input>
        <wsoap12:body use="literal"/>
      </wsdl:input>
      <wsdl:output>
        <wsoap12:body use="literal"/>
      </wsdl:output>
    </wsdl:operation>
  </wsdl:binding>

  <wsdl:service name="getMarketingCampaign_Service">
    <wsdl:port name="getMarketingCampaign_Port" binding="tns:getMarketingCampaign_SOAP12Binding">
      <wsoap12:address location="sb://INT-SIE-EAI_getMarketingCampaign_RA"/>
    </wsdl:port>
  </wsdl:service>

</wsdl:definitions>