-------------------------------------------------------
--  DDL for Table ESB_CAPABILITY_DETAILS
--------------------------------------------------------

ALTER TABLE ESB_CAPABILITY_DETAILS DROP CONSTRAINT ESB_CAPABILITY_TYPE_FK;
ALTER TABLE ESB_CAPABILITY_DETAILS
 ADD CONSTRAINT "ESB_CAPABILITY_TYPE_FK" FOREIGN KEY ("DETAIL_TYPE_ID")
    REFERENCES "ESB_CAPABILITY_DETAILS_TYPE" ("ID")

COMMIT;