--------------------------------------------------------
--  DDL for Table ESB_CORRELATION_GROUP
--------------------------------------------------------
  
  CREATE TABLE "ESB_CORRELATION_GROUP" 
  (	
	"ID" NUMBER NOT NULL, 
	"NAME" VARCHAR2(100) NOT NULL, 	
	"REQUESTHEADER" CLOB,
	"DESCRIPTION" VARCHAR2(255), 
	"RCD_STATUS" NUMBER(1,0) DEFAULT 1 NOT NULL,
	"CREATIONDATE" DATE DEFAULT CURRENT_DATE,
	CONSTRAINT "ESB_CORRELATION_GROUP_PK" PRIMARY KEY ("ID")
  );
  COMMENT ON COLUMN "ESB_CORRELATION_GROUP"."RCD_STATUS" IS '1=ACTIVE, 0=INACTIVE';