  CREATE TABLE "ESB_ERROR_DERIVATION_CONF" 
   (
	"ID" NUMBER NOT NULL, 
	"COUNT_PRIORITY_1" NUMBER NOT NULL, 
	"COUNT_PRIORITY_2" NUMBER NOT NULL, 
    "COUNT_PRIORITY_3" NUMBER NOT NULL, 
	"RUN_STATE" VARCHAR2(20 BYTE) NOT NULL, 
	"RCD_STATUS" NUMBER(1,0) DEFAULT 1 NOT NULL, 	
	"CREATIONDATE" DATE DEFAULT CURRENT_DATE,
	CONSTRAINT "ESB_ERROR_DERIVATION_CONF" PRIMARY KEY ("ID")
	);
	COMMENT ON COLUMN "ESB_ERROR_DERIVATION_CONF"."RCD_STATUS" IS '1=ACTIVE, 0=INACTIVE';
	