--------------------------------------------------------
--  DDL for Table ESB_CONSUMER_CAP_DETAILS_TYPE
--------------------------------------------------------
  CREATE TABLE "ESB_CONSUMER_CAP_DETAILS_TYPE" 
   (
    "ID" NUMBER NOT NULL, 
	"NAME" VARCHAR2(50 BYTE), 
	"DESCRIPTION" VARCHAR2(200 BYTE), 
	"CREATIONDATE" DATE DEFAULT CURRENT_DATE, 
	"RCD_STATUS" NUMBER(1,0) DEFAULT 1 NOT NULL, 
	 CONSTRAINT "ESB_CONSUMER_CAP_DETAILS_TYPE" PRIMARY KEY ("ID")
	);
  
   COMMENT ON COLUMN "ESB_CONSUMER_DETAILS_TYPE"."RCD_STATUS" IS '1=ACTIVE, 0=INACTIVE';