--------------------------------------------------------
--  DDL for Table ESB_ERROR_MAPPING	
--------------------------------------------------------
  
  CREATE TABLE "ESB_ERROR_MAPPING" 
   (
	"ID" NUMBER NOT NULL, 
	"ERROR_SOURCE" NUMBER NOT NULL,
	"MODULE" VARCHAR2(50 BYTE),
	"SUB_MODULE" VARCHAR2(50 BYTE),
	"RAW_CODE" VARCHAR2(25 BYTE), 
	"RAW_DESCRIPTION" VARCHAR2(500 BYTE), 
	"CAN_ERR_ID" NUMBER NOT NULL, 
	"STATUS_ID" NUMBER NOT NULL,
	"RCD_STATUS" NUMBER(1,0) DEFAULT 1 NOT NULL,
	"CREATIONDATE" DATE DEFAULT CURRENT_DATE,
	 CONSTRAINT "ESB_ERROR_MAPPING_PK" PRIMARY KEY ("ID"),
	 CONSTRAINT "ESB_ERROR_MAPPING_CANONICAL_FK" FOREIGN KEY ("CAN_ERR_ID") REFERENCES "ESB_CANONICAL_ERROR" ("ID"),
	 CONSTRAINT "ESB_ERROR_MAPPING_SYSTEM_FK" FOREIGN KEY ("ERROR_SOURCE") REFERENCES "ESB_SYSTEM" ("ID"),
	 CONSTRAINT "ESB_ERROR_MAPPING_STATUS_FK" FOREIGN KEY ("STATUS_ID") REFERENCES "ESB_ERROR_STATUS_TYPE" ("ID")
   );
   COMMENT ON COLUMN "ESB_ERROR_MAPPING"."RCD_STATUS" IS '1=ACTIVE, 0=INACTIVE';