--------------------------------------------------------
--  DDL for Table ESB_RETRY_NOTIFICATION
--------------------------------------------------------
  
  CREATE TABLE "ESB_RETRY_NOTIFICATION" 
   (
	"ID" NUMBER NOT NULL, 
	"TRANSACTION_CHECK_ID" NUMBER NOT NULL,
	CONSTRAINT "ESB_RETRY_NOTIFICATION_PK" PRIMARY KEY ("ID"),
  	CONSTRAINT "ESB_RETRY_NOTI_TX_CHECK_FK" FOREIGN KEY ("TRANSACTION_CHECK_ID")
	  REFERENCES "ESB_TRANSACTION_CHECK" ("ID")
   );
