--------------------------------------------------------
--  DDL for Table ESB_CONSUMER_CAP_DETAILS
--------------------------------------------------------
  

  CREATE TABLE "ESB_CONSUMER_CAP_DETAILS" 
  (	
	"ID" NUMBER NOT NULL,
	"CAPABILITY_ID" NUMBER, 
	"CONSUMER_ID" NUMBER NOT NULL, 
	"CONTEXT" VARCHAR2(255 BYTE), 
	"DETAIL_TYPE_ID" NUMBER NOT NULL,  
	"DETAIL_CONTENT" CLOB,  
	"RCD_STATUS" NUMBER(1,0) DEFAULT 1 NOT NULL, 
	"CREATIONDATE" DATE DEFAULT CURRENT_DATE,
	CONSTRAINT "ESB_CONSUMER_CAP_DETAILS_PK" PRIMARY KEY ("ID"),
	CONSTRAINT "ESB_CONSUMER_CAP_CAP_FK" FOREIGN KEY ("CAPABILITY_ID")
		REFERENCES "ESB_CAPABILITY" ("ID") ON DELETE CASCADE, 
	CONSTRAINT "ESB_CONSUMER_CAP_CONS_FK" FOREIGN KEY ("CONSUMER_ID")
		REFERENCES "ESB_CONSUMER" ("ID"),
	CONSTRAINT "ESB_CONSUMER_CAP_PROP_FK" FOREIGN KEY ("DETAIL_TYPE_ID")
		REFERENCES "ESB_CONSUMER_CAP_DETAILS_TYPE" ("ID"),	
	CONSTRAINT "ESB_CONSU_CAP_STATUS_CK" CHECK ("RCD_STATUS" IN(0,1))
  );
  COMMENT ON COLUMN "ESB_CONSUMER_CAP_DETAILS"."RCD_STATUS" IS '1=ACTIVE, 0=INACTIVE';