--------------------------------------------------------
--  DDL for Table ESB_CORRELATION_INSTANCE
--------------------------------------------------------
  
  CREATE TABLE "ESB_CORRELATION_INSTANCE" 
  (	
	"ID" NUMBER NOT NULL, 
	"CORRELATION_ID" VARCHAR2(255) NOT NULL, 
	"MEMBER_NAME" VARCHAR2(100) NOT NULL, 
	"MEMBER_ADDRESS" VARCHAR2(255), 
	"RCD_STATUS" NUMBER(1,0) DEFAULT 1 NOT NULL,
	"CREATIONDATE" DATE DEFAULT CURRENT_DATE,
	CONSTRAINT "ESB_CORRELATION_INSTANCE_PK" PRIMARY KEY ("ID")
  );
  COMMENT ON COLUMN "ESB_CORRELATION_INSTANCE"."RCD_STATUS" IS '1=ACTIVE, 0=INACTIVE';