--------------------------------------------------------
--  DDL for Table ESB_CONVERSATION_STATUS
--------------------------------------------------------
  
  CREATE TABLE "ESB_CONVERSATION_STATUS" 
  (	
	"CONVERSATION_ID" VARCHAR2(100 BYTE) NOT NULL, 
	"STATUS" VARCHAR2(30 BYTE) DEFAULT 'PENDING', 
	"RSP_MSG" CLOB, 
	"CAN_ERR_ID" NUMBER, 
	"CREATION_TIMESTAMP" TIMESTAMP, 
	"UPDATE_TIMESTAMP" TIMESTAMP, 
	"UPDATE_COMPONENT" VARCHAR2(50),
	"UPDATE_OPERATION" VARCHAR2(50),
	"RCD_STATUS" NUMBER(1,0) DEFAULT 1 NOT NULL, 
	"CREATIONDATE" DATE DEFAULT CURRENT_DATE,
	CONSTRAINT "ESB_CONVERSATION_STATUS_PK" PRIMARY KEY ("CONVERSATION_ID"), 
	CONSTRAINT "ESB_CONVERSATION_STATUS_CK" CHECK ("RCD_STATUS" IN(0,1))
  );
  COMMENT ON COLUMN "ESB_CONVERSATION_STATUS"."RCD_STATUS" IS '1=ACTIVE, 0=INACTIVE';