--------------------------------------------------------
--  DDL for Table ESB_CONSUMER
--------------------------------------------------------

  CREATE TABLE "ESB_CONSUMER" 
   (
	"ID" NUMBER NOT NULL, 
	"SYSCODE" NUMBER NOT NULL, 
	"COUNTRY_ID" NUMBER NOT NULL, 
	"ENT_CODE" NUMBER NOT NULL, 
	"RCD_STATUS" NUMBER(1,0) DEFAULT 1 NOT NULL, 
	"CREATIONDATE" DATE DEFAULT CURRENT_DATE,
	 CONSTRAINT "ESB_CONSUMER_PK" PRIMARY KEY ("ID"),
	 CONSTRAINT "ESB_CONSUMER_SYSTEM_FK" FOREIGN KEY ("SYSCODE")
	  REFERENCES "ESB_SYSTEM" ("ID"), 
	 CONSTRAINT "ESB_CONSUMER_COUNTRY_FK" FOREIGN KEY ("COUNTRY_ID")
	  REFERENCES "ESB_COUNTRY" ("ID"), 
	 CONSTRAINT "ESB_CONSUMER_ENT_FK" FOREIGN KEY ("ENT_CODE")
	  REFERENCES "ESB_ENTERPRISE" ("ID"),
	 CONSTRAINT "ESB_CONSUMER_STATUS_CK" CHECK ("RCD_STATUS" IN(0,1))
   );
   COMMENT ON COLUMN "ESB_CONSUMER"."RCD_STATUS" IS '1=ACTIVE, 0=INACTIVE';
