--------------------------------------------------------
--  DDL for Table ESB_SYSTEM_API_OPERATION
--------------------------------------------------------

  CREATE TABLE "ESB_SYSTEM_API_OPERATION" 
   (
	"ID" NUMBER NOT NULL, 
	"SYSTEM_API_ID" NUMBER NOT NULL, 
	"VERSION" VARCHAR2(10 BYTE) NOT NULL, 
	"NAME" VARCHAR2(50 BYTE), 
	"DESCRIPTION" VARCHAR2(100 BYTE), 
	"RCD_STATUS" NUMBER(1,0) DEFAULT 1 NOT NULL, 
	"CREATIONDATE" DATE DEFAULT CURRENT_DATE,
	CONSTRAINT "ESB_SYSTEM_API_OPERATION_PK" PRIMARY KEY ("ID"),
	CONSTRAINT "ESB_SYSTEM_API_OPERATION_FK1" FOREIGN KEY ("SYSTEM_API_ID")
		REFERENCES "ESB_SYSTEM_API" ("ID"), 
	CONSTRAINT "ESB_SYSTEM_API_OPERATION_RS_CK" CHECK ("RCD_STATUS" IN(0,1))
   );
   COMMENT ON COLUMN "ESB_SYSTEM_API_OPERATION"."RCD_STATUS" IS '1=ACTIVE, 0=INACTIVE';