--------------------------------------------------------
--  DDL for Table ESB_SYSTEM_API
--------------------------------------------------------

  CREATE TABLE "ESB_SYSTEM_API" 
   (
	"ID" NUMBER NOT NULL, 
	"SYSTEM_ID" NUMBER NOT NULL, 
	"CODE" VARCHAR2(20 BYTE) NOT NULL, 
	"NAME" VARCHAR2(50 BYTE), 
	"DESCRIPTION" VARCHAR2(100 BYTE), 
	"RCD_STATUS" NUMBER(1,0) DEFAULT 1 NOT NULL, 
	"CREATIONDATE" DATE DEFAULT CURRENT_DATE,
	CONSTRAINT "ESB_SYSTEM_API_PK" PRIMARY KEY ("ID"),
	CONSTRAINT "ESB_SYSTEM_API_FK1" FOREIGN KEY ("SYSTEM_ID")
		REFERENCES "ESB_SYSTEM" ("ID"), 
	CONSTRAINT "ESB_SYSTEM_API_STATUS_CK" CHECK ("RCD_STATUS" IN(0,1))
   );
   COMMENT ON COLUMN "ESB_SYSTEM_API"."RCD_STATUS" IS '1=ACTIVE, 0=INACTIVE';