<?xml version= '1.0' encoding= 'UTF-8' ?>
<wsdl:definitions
     name="RetryTreatment"
     targetNamespace="http://www.entel.cl/ESO/RetryTreatment/v1"
     xmlns:xsd="http://www.w3.org/2001/XMLSchema"
     xmlns:bpws="http://docs.oasis-open.org/wsbpel/2.0/process/executable"
     xmlns:plnk="http://docs.oasis-open.org/wsbpel/2.0/plnktype"
     xmlns:tns="http://www.entel.cl/ESO/RetryTreatment/v1"
     xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/"
    >
    <plnk:partnerLinkType name="RetryTreatment_Register_direct">
        <plnk:role name="RetryTreatment_PortType" portType="tns:RetryTreatment_PortType"/>
    </plnk:partnerLinkType>
    <wsdl:import namespace="http://www.entel.cl/ESO/RetryTreatment/v1"
                 location="oramds:/apps/Commons/DC_SC_ErrorManager/ErrorHospital/WSDL/RetryTreatment.wsdl"/>
</wsdl:definitions>
