<wsdl:definitions targetNamespace="http://www.entel.cl/RA/INT-SIE-MAR/createUpdateMarketingCampaign/v1" xmlns:tns="http://www.entel.cl/RA/INT-SIE-MAR/createUpdateMarketingCampaign/v1" xmlns:xs="http://www.w3.org/2001/XMLSchema" xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/" xmlns:wsoap12="http://schemas.xmlsoap.org/wsdl/soap12/" xmlns:ns="http://schemas.xmlsoap.org/soap/encoding/" xmlns:csmns="http://www.entel.cl/CSM/RA/INT-SIE-MAR/createUpdateMarketingCampaign/v1">
  <wsdl:types>
    <xs:schema xmlns:xsd="http://www.w3.org/2001/XMLSchema">
      <xs:import namespace="http://www.entel.cl/CSM/RA/INT-SIE-MAR/createUpdateMarketingCampaign/v1"
                 schemaLocation="INT-SIE-MAR_createUpdateMarketingCampaign_v1_CSM.xsd"/>
    </xs:schema>
  </wsdl:types>

  <wsdl:message name="createUpdateMarketingCampaign_Message_In">
    <wsdl:part name="In" element="csmns:INT-SIE-MAR_createUpdateMarketingCampaign_REQ"/>
  </wsdl:message>
  
  <wsdl:message name="createUpdateMarketingCampaign_Message_Out">
    <wsdl:part name="Out" element="csmns:INT-SIE-MAR_createUpdateMarketingCampaign_RSP"/>
  </wsdl:message>
  
 
  <wsdl:portType name="createUpdateMarketingCampaign_PortType">
    <wsdl:operation name="createUpdateMarketingCampaign">
      <wsdl:input message="tns:createUpdateMarketingCampaign_Message_In"/>
      <wsdl:output message="tns:createUpdateMarketingCampaign_Message_Out"/>
    </wsdl:operation>
  </wsdl:portType>

  
  <wsdl:binding name="createUpdateMarketingCampaign_SOAP12Binding" type="tns:createUpdateMarketingCampaign_PortType">
    <wsoap12:binding style="document" transport="http://www.bea.com/wli/sb/transports/sb"/>
    <wsdl:operation name="createUpdateMarketingCampaign">
      <wsoap12:operation style="document" soapAction=""/>
      <wsdl:input>
        <wsoap12:body use="literal"/>
      </wsdl:input>
      <wsdl:output>
        <wsoap12:body use="literal"/>
      </wsdl:output>
    </wsdl:operation>
  </wsdl:binding>

  <wsdl:service name="createUpdateMarketingCampaign_Service">
    <wsdl:port name="createUpdateMarketingCampaign_Port" binding="tns:createUpdateMarketingCampaign_SOAP12Binding">
      <wsoap12:address location="sb://INT-SIE-MAR_createUpdateMarketingCampaign_RA"/>
    </wsdl:port>
  </wsdl:service>

</wsdl:definitions>