SPOOL salida_DROP_ALL_PACKAGES.txt
@DROP_ESB_CONVERSATION_MANAGER_PKG.sql
@DROP_ESB_CORRELATIONMANAGER_PKG.sql
@DROP_ESB_ERROR_HOSPITAL_PKG.sql
@DROP_ESB_ERROR_MANAGER_PKG.sql
@DROP_ESB_LOGGERMANAGER_PKG.sql
@DROP_ESB_MESSAGEMANAGER_PKG.sql
@DROP_ESB_PARAMETERMANAGER_PKG.sql

--------------------------------------------------------
--  RETRYMANAGER
--------------------------------------------------------
@DROP_ESB_RETRY_MANAGER_PKG.sql
SPOOL OFF;
