<?xml version= '1.0' encoding= 'UTF-8' ?>
<wsdl:definitions
     name="Treatment"
     targetNamespace="http://www.entel.cl/ESO/Treatment/Generic/v1"
     xmlns:tns="http://www.entel.cl/ESO/Treatment/Generic/v1"
     xmlns:xs="http://www.w3.org/2001/XMLSchema"
     xmlns:msg="http://www.entel.cl/ESO/ErrorTreatment/Generic/v1"
     xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/"
     xmlns:wsoap12="http://schemas.xmlsoap.org/wsdl/soap12/"
    >
    <wsdl:types>
        <xs:schema xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns:tns="http://www.entel.cl/ESO/Treatment/Generic/v1"
             xmlns:xs="http://www.w3.org/2001/XMLSchema" xmlns:msg="http://www.entel.cl/ESO/ErrorTreatment/Generic/v1"
             xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/" xmlns:wsoap12="http://schemas.xmlsoap.org/wsdl/soap12/">
            <xs:import namespace="http://www.entel.cl/ESO/ErrorTreatment/Generic/v1" schemaLocation="../Schemas/Treatment_v1_ESO.xsd"/>
        </xs:schema>
    </wsdl:types>
    <wsdl:message name="Treatment">
        <wsdl:part name="In" element="msg:Treatment"/>
    </wsdl:message>
    <wsdl:portType name="Treatment_PortType">
        <wsdl:operation name="process">
            <wsdl:input message="tns:Treatment"/>
        </wsdl:operation>
    </wsdl:portType>
</wsdl:definitions>