<?xml version= '1.0' encoding= 'UTF-8' ?>
<wsdl:definitions
     name="ESB_ERROR_DISPATCHER_pull"
     targetNamespace="http://xmlns.oracle.com/pcbpel/adapter/db/DC_SC_ErrorManager/ErrorHandler/ESB_ERROR_DISPATCHER_pull"
     xmlns:tns="http://xmlns.oracle.com/pcbpel/adapter/db/DC_SC_ErrorManager/ErrorHandler/ESB_ERROR_DISPATCHER_pull"
     xmlns:jca="http://xmlns.oracle.com/pcbpel/wsdl/jca/"
     xmlns:plt="http://schemas.xmlsoap.org/ws/2003/05/partner-link/"
     xmlns:pc="http://xmlns.oracle.com/pcbpel/"
     xmlns:top="http://xmlns.oracle.com/pcbpel/adapter/db/top/ESB_ERROR_DISPATCHER_pull"
     xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/"
     xmlns:ns1="http://www.entel.cl/ESO/NotificationTreatment/v1"
     xmlns:ns2="http://www.entel.cl/ESO/Treatment/Generic/v1"
    >
    <plt:partnerLinkType name="ESB_ERROR_DISPATCHER_pull_plt">
        <plt:role name="ESB_ERROR_DISPATCHER_pull_role">
            <plt:portType name="tns:ESB_ERROR_DISPATCHER_pull_ptt"/>
        </plt:role>
    </plt:partnerLinkType>
    <wsdl:import namespace="http://www.entel.cl/ESO/NotificationTreatment/v1" location="oramds:/apps/Commons/DC_SC_ErrorManager/ErrorHospital/WSDL/NotificationTreatment.wsdl"/>
    <wsdl:import namespace="http://www.entel.cl/ESO/Treatment/Generic/v1" location="ErrorDispatcherTreatment.wsdl"/>
    <wsdl:types>
        <schema xmlns="http://www.w3.org/2001/XMLSchema">
            <import namespace="http://xmlns.oracle.com/pcbpel/adapter/db/top/ESB_ERROR_DISPATCHER_pull"
                 schemaLocation="../Schemas/ESB_ERROR_DISPATCHER_pull_table.xsd"/>
        </schema>
    </wsdl:types>
    <wsdl:message name="EsbErrorDispatcherCollection_msg">
        <wsdl:part name="EsbErrorDispatcherCollection" element="top:EsbErrorDispatcherCollection"/>
    </wsdl:message>
    <wsdl:portType name="ESB_ERROR_DISPATCHER_pull_ptt">
        <wsdl:operation name="receive">
            <wsdl:input message="tns:EsbErrorDispatcherCollection_msg"/>
        </wsdl:operation>
    </wsdl:portType>
</wsdl:definitions>
