DROP TYPE TRACE_T FORCE;
DROP TYPE TARGET_T FORCE;
DROP TYPE SUBM_T FORCE;
DROP TYPE SOURCERROR_T FORCE;
DROP TYPE SOURCEERRORS_T FORCE;
DROP TYPE SOURCEERROR_T FORCE;
DROP TYPE SERVICE_T FORCE;
DROP TYPE SECURITYCREDENTIAL_T FORCE;
DROP TYPE SECURITYASSERTIONS_T FORCE;
DROP TYPE SECURITYASSERTION_T FORCE;
DROP TYPE RESULT_T FORCE;
DROP TYPE QUALITYOFSERVICE_T FORCE;
DROP TYPE PLACEHOLDER_T FORCE;
DROP TYPE PARAMETER_T FORCE;
DROP TYPE MODULE_T FORCE;
DROP TYPE MEMBER_T_CUR FORCE;
DROP TYPE MEMBER_T FORCE;
DROP TYPE MAPS_OUT_T FORCE;
DROP TYPE MAPS_IN_T FORCE;
DROP TYPE MAP_OUT_T FORCE;
DROP TYPE MAP_IN_T FORCE;
DROP TYPE LOGMODE_T FORCE;
DROP TYPE LOG_T FORCE;
DROP TYPE KEYVALUETABLE_T FORCE;
DROP TYPE KEYVALUE_T FORCE;
DROP TYPE KEYS_T FORCE;
DROP TYPE HEADERTRACER_T FORCE;
DROP TYPE HEADER_T FORCE;
DROP TYPE ERRORSOURCEDETAILS_T FORCE;
DROP TYPE ERRORINDEX_T FORCE;
DROP TYPE ERRORDETAILS_T FORCE;
DROP TYPE ERRORDETAIL_T FORCE;
DROP TYPE ERROR_T FORCE;
DROP TYPE CONSUMER_T FORCE;
DROP TYPE CHANNEL_T FORCE;
DROP TYPE CANONICALERROR_T FORCE;
DROP TYPE AUDIT_T FORCE;
DROP TYPE CONTEXTMETADATA_T FORCE;
DROP TYPE LOGGER_T FORCE;

--------------------------------------------------------
--  RETRYMANAGER
--------------------------------------------------------
DROP TYPE RETRYMANAGER_ID_T_CUR;
DROP TYPE RETRYMANAGER_STATUS_T_CUR;