ALTER TYPE TRACE_T COMPILE;
ALTER TYPE TARGET_T COMPILE;
ALTER TYPE SUBM_T COMPILE;
ALTER TYPE SOURCERROR_T COMPILE;
ALTER TYPE SOURCEERRORS_T COMPILE;
ALTER TYPE SOURCEERROR_T COMPILE;
ALTER TYPE SERVICE_T COMPILE;
ALTER TYPE SECURITYCREDENTIAL_T COMPILE;
ALTER TYPE SECURITYASSERTIONS_T COMPILE;
ALTER TYPE SECURITYASSERTION_T COMPILE;
ALTER TYPE RESULT_T COMPILE;
ALTER TYPE QUALITYOFSERVICE_T COMPILE;
ALTER TYPE PLACEHOLDER_T COMPILE;
ALTER TYPE PARAMETER_T COMPILE;
ALTER TYPE MODULE_T COMPILE;
ALTER TYPE MEMBER_T_CUR COMPILE;
ALTER TYPE MEMBER_T COMPILE;
ALTER TYPE MAPS_OUT_T COMPILE;
ALTER TYPE MAPS_IN_T COMPILE;
ALTER TYPE MAP_OUT_T COMPILE;
ALTER TYPE MAP_IN_T COMPILE;
ALTER TYPE LOGMODE_T COMPILE;
ALTER TYPE LOG_T COMPILE;
ALTER TYPE KEYVALUETABLE_T COMPILE;
ALTER TYPE KEYVALUE_T COMPILE;
ALTER TYPE KEYS_T COMPILE;
ALTER TYPE HEADERTRACER_T COMPILE;
ALTER TYPE HEADER_T COMPILE;
ALTER TYPE ERRORSOURCEDETAILS_T COMPILE;
ALTER TYPE ERRORINDEX_T COMPILE;
ALTER TYPE ERRORDETAILS_T COMPILE;
ALTER TYPE ERRORDETAIL_T COMPILE;
ALTER TYPE ERROR_T COMPILE;
ALTER TYPE CONSUMER_T COMPILE;
ALTER TYPE CHANNEL_T COMPILE;
ALTER TYPE CANONICALERROR_T COMPILE;
ALTER TYPE AUDIT_T COMPILE;
ALTER TYPE CONTEXTMETADATA_T COMPILE;
ALTER TYPE LOGGER_T COMPILE;

--------------------------------------------------------
--  RETRYMANAGER
--------------------------------------------------------

ALTER TYPE RETRYMANAGER_ID_T_CUR;
ALTER TYPE RETRYMANAGER_STATUS_T_CUR;