SPOOL salida_CREATE_ALL_PACKAGES.txt
	@ALTER_ESB_RETRY_MANAGER_PKG_SPEC.sql
	@ALTER_ESB_RETRY_MANAGER_PKG_BODY.sql
	@ALTER_LOGGERMANAGER_PKG_BODY.sql
	@ALTER_MESSAGEMANAGER_PKG_SPEC.sql
	@ALTER_MESSAGEMANAGER_PKG_BODY.sql
	@ALTER_ESB_ERROR_MANAGER_PKG_SPEC.sql
	@ALTER_ESB_ERROR_MANAGER_PKG_BODY.sql
SPOOL OFF;
