create or replace PACKAGE "ESB_RETRY_MANAGER_PKG" AS 
-- REGISTRA UNA TRASACCION PARA QUE TENGA RE INTENTOS 
  PROCEDURE SP_REGISTER_RETRY 
  ( P_ERROR_TREATMENT_ID IN NUMBER ,
    P_FECHA IN TIMESTAMP,
  	p_SOURCE_ERROR_DESC OUT VARCHAR2, 
  	p_SOURCE_ERROR_CODE OUT VARCHAR2);   

-- INFORMA EL ESTADO DE UNA TRASANCCION EN REINTENTOS    
  PROCEDURE SP_CHECK_RETRY_STATUS
    ( P_CONVERSATION_ID IN VARCHAR2 ,
    p_STATUS OUT VARCHAR2, 
    p_SOURCE_ERROR_DESC OUT VARCHAR2, 
    p_SOURCE_ERROR_CODE OUT VARCHAR2);

-- ACTUALIZA EL ESTADO DE LAS TRASANCCION EN REINTENTOS CON LOS ESTADOS INFORMADOS    
  PROCEDURE SP_RETRY_UPDATE_STATUS
    ( P_IDS IN RETRYMANAGER_ID_T_CUR ,
    P_STATUS IN RETRYMANAGER_STATUS_T_CUR,
    P_SOURCE_ERROR_DESC OUT VARCHAR2, 
    P_SOURCE_ERROR_CODE OUT VARCHAR2);
    
-- REGISTRA LA EJUCUCION DE UN NUEVO REINTENTO    
  PROCEDURE SP_REGISTER_NEW_RETRY
    ( P_ERROR_TREATMENT_ID IN NUMBER , 
    P_URL OUT VARCHAR2, 
    P_ACTION OUT VARCHAR2, 
    P_MAX_RETRY OUT NUMBER, 
    P_CAPABILITY OUT VARCHAR2, 
    P_NUMBER_RETRY OUT NUMBER, 
    P_ID_ESB_RETRYMANAGER_HISTORY OUT NUMBER,
    P_SOURCE_ERROR_DESC OUT VARCHAR2, 
    P_SOURCE_ERROR_CODE OUT VARCHAR2);
    
-- REGISTRA EL RESULTADO DE UN NUEVO REINTENTO  
  PROCEDURE SP_REGISTER_RETRY_RESULT
  ( P_ERROR_RETRYMANAGER_ID IN NUMBER ,
  P_ID_ESB_RETRYMANAGER_HISTORY IN NUMBER,
  P_FECHA IN TIMESTAMP,
  p_STATUS IN VARCHAR2, 
  p_SOURCE_ERROR_DESC OUT VARCHAR2, 
  p_SOURCE_ERROR_CODE OUT VARCHAR2);   
  
    
-- INFORMA EL ESTADO DE UNA TRASANCCION EN REINTENTOS    
  PROCEDURE SP_REGISTER_STATUS
    ( P_CONVERSATION_ID IN VARCHAR2 ,
    P_CORRELATION_ID IN VARCHAR2, 
    P_STATUS IN VARCHAR2, 
    P_SOURCE_ERROR_DESC OUT VARCHAR2, 
    P_SOURCE_ERROR_CODE OUT VARCHAR2);

  PROCEDURE SP_RETRY_CONF_CONV
    ( P_CONVERSATION_ID IN VARCHAR2 ,
    P_CORRELATION_ID IN VARCHAR2, 
    P_MAX_RETRY OUT NUMBER, 
    P_INTERVAL_TIME OUT NUMBER, 
    P_SOURCE_ERROR_DESC OUT VARCHAR2, 
    P_SOURCE_ERROR_CODE OUT VARCHAR2);
  
  PROCEDURE SP_RETRY_INFO_CONV
    ( P_CONVERSATION_ID IN VARCHAR2 ,
    P_CORRELATION_ID IN VARCHAR2, 
    P_RETRY_COUNT OUT NUMBER, 
    P_STATUS OUT VARCHAR, 
    P_SOURCE_ERROR_DESC OUT VARCHAR2, 
    P_SOURCE_ERROR_CODE OUT VARCHAR2);

END ESB_RETRY_MANAGER_PKG;