--------------------------------------------------------
--  DDL for Package ESB_MESSAGEMANAGER_PKG
--------------------------------------------------------
create or replace 
PACKAGE ESB_MESSAGEMANAGER_PKG AS 
  PROCEDURE GETCAPABILITYCHECKSTATUS(p_SERVICE_CODE IN VARCHAR2, p_SERVICE_NAME IN VARCHAR2, p_SERVICE_OPERATION IN VARCHAR2, CHECK_MESSAGE OUT NUMBER, CAPABILITY_ID OUT NUMBER);
  PROCEDURE GETCAPABILITYCHECKS(p_SERVICE_CODE IN VARCHAR2, p_SERVICE_NAME IN VARCHAR2, p_SERVICE_OPERATION IN VARCHAR2, CHECK_TYPES OUT SYS_REFCURSOR);
  PROCEDURE GETDEFAULTCHECKS(p_CHECK_TYPE IN NUMBER, CHECK_TYPES OUT SYS_REFCURSOR);
  PROCEDURE GETMESSAGESTATUS(p_EVENT_ID IN VARCHAR2, p_PROC_ID IN VARCHAR2, p_CLIENT_REQ_TIMESTAMP IN TIMESTAMP WITH TIME ZONE, p_CAPABILITY_ID IN NUMBER, MESSAGE_TRANSACTION OUT SYS_REFCURSOR);
  PROCEDURE GETTRANSACTIONINFO(p_EVENT_ID IN VARCHAR2, p_PROC_ID IN VARCHAR2, p_CLIENT_REQ_TIMESTAMP IN TIMESTAMP WITH TIME ZONE, p_CAPABILITY_ID IN NUMBER, MESSAGE_TRANSACTION OUT SYS_REFCURSOR);
  PROCEDURE GETCHECKTRANSACTION(p_EVENT_ID IN VARCHAR2, p_PROC_ID IN VARCHAR2, p_CLIENT_REQ_TIMESTAMP IN TIMESTAMP WITH TIME ZONE, p_CAPABILITY_ID IN NUMBER, TRANSACTION_CHECK OUT SYS_REFCURSOR);
  PROCEDURE REGISTRYTRANSACTION(p_EVENT_ID IN VARCHAR2, p_PROC_ID IN VARCHAR2, p_CLIENT_REQ_TIMESTAMP IN VARCHAR2, p_CAPABILITY_ID IN NUMBER, p_CONVERSATION_ID IN VARCHAR2, RESULT_ID OUT NUMBER);
  PROCEDURE UPDATETRANSACTION(p_EVENT_ID IN VARCHAR2, p_PROC_ID IN VARCHAR2, p_CLIENT_REQ_TIMESTAMP IN VARCHAR2, p_CAPABILITY_ID IN NUMBER, p_NEWSTATUS IN NUMBER, RESULT_ID OUT NUMBER);
  PROCEDURE REGISTRYTRANSACTIONCHECK(p_MESSAGE_TX_ID IN NUMBER, p_CONVERSATION_ID IN VARCHAR2, p_RESPONSE_MSG IN CLOB, p_RESULT_CODE IN VARCHAR2, p_RESULT_DESC IN VARCHAR2, RESULT_ID OUT NUMBER);
END ESB_MESSAGEMANAGER_PKG;

/