SET ECHO ON
SET DEFINE OFF
SET SERVEROUTPUT ON
WHENEVER SQLERROR CONTINUE ROLLBACK

DECLARE

BEGIN

	BEGIN
		DELETE FROM  ESB_PARAMETER WHERE KEY = 'LogSeveritySet' AND VALUE = 'DEBUG,INFO,WARNING' AND RCD_STATUS = '1';
	END;
	
END;
/

COMMIT;