SET ECHO ON
SET DEFINE OFF
SET SERVEROUTPUT ON
WHENEVER SQLERROR CONTINUE ROLLBACK

DECLARE

BEGIN

	BEGIN
		DELETE FROM ESB_LOG_TYPE WHERE ID = (SELECT ID FROM ESB_LOG_TYPE WHERE NAME = 'SREQ' AND DESCRIPTION = 'Service Request' AND RCD_STATUS = '1');
	END;
	
	BEGIN
		DELETE FROM ESB_LOG_TYPE WHERE ID = (SELECT ID FROM ESB_LOG_TYPE WHERE NAME = 'SRSP' AND DESCRIPTION = 'Service Response' AND RCD_STATUS = '1');
	END;
	
	BEGIN
		DELETE from ESB_LOG_TYPE WHERE ID = (SELECT ID FROM ESB_LOG_TYPE WHERE NAME = 'CSRSP' AND DESCRIPTION = 'CallBack Service Response' AND RCD_STATUS = '1');
	END;

	BEGIN
		DELETE FROM ESB_LOG_TYPE WHERE ID = (SELECT ID FROM ESB_LOG_TYPE WHERE NAME = 'LOG' AND DESCRIPTION = 'Generic Log' AND RCD_STATUS = '1');
	END;
	
	BEGIN
		DELETE FROM ESB_LOG_TYPE WHERE ID = (SELECT ID FROM ESB_LOG_TYPE WHERE NAME = 'LREQ' AND DESCRIPTION = 'Legacy Service Request' AND RCD_STATUS = '1');
	END;
	
	BEGIN
		DELETE FROM ESB_LOG_TYPE WHERE ID = (SELECT ID FROM ESB_LOG_TYPE WHERE NAME = 'LRSP' AND DESCRIPTION = 'Legacy Service Response' AND RCD_STATUS = '1');
	END;
	
END;
/

COMMIT;
