SET ECHO ON
SET DEFINE OFF
SET SERVEROUTPUT ON
WHENEVER SQLERROR CONTINUE ROLLBACK

DECLARE

BEGIN

	BEGIN
		DELETE FROM ESB_CORRELATION_MEMBER_TYPE WHERE ID = (SELECT ID FROM ESB_CORRELATION_MEMBER_TYPE WHERE NAME = 'GroupOwner');
	END;
	
	BEGIN
		DELETE FROM ESB_CORRELATION_MEMBER_TYPE WHERE ID = (SELECT ID FROM ESB_CORRELATION_MEMBER_TYPE WHERE NAME = 'GroupController');
	END;
	
	BEGIN
		DELETE FROM ESB_CORRELATION_MEMBER_TYPE WHERE ID = (SELECT ID FROM ESB_CORRELATION_MEMBER_TYPE WHERE NAME = 'GroupProvider');
	END;
	
	BEGIN
		DELETE FROM ESB_CORRELATION_MEMBER_TYPE WHERE ID = (SELECT ID FROM ESB_CORRELATION_MEMBER_TYPE WHERE NAME = 'GroupConsumer');
	END;

END;
/

COMMIT;
