SET ECHO ONSET DEFINE OFFSET SERVEROUTPUT ONWHENEVER SQLERROR CONTINUE ROLLBACKDECLAREBEGIN
	BEGIN		DELETE FROM ESB_ERROR_STATUS_TYPE WHERE ID = (SELECT ID FROM ESB_ERROR_STATUS_TYPE WHERE NAME = 'OK' AND DESCRIPTION = 'Transaccion que finaliza exitosamente.' AND RCD_STATUS = '1');	END;
	BEGIN		DELETE FROM ESB_ERROR_STATUS_TYPE WHERE ID = (SELECT ID FROM ESB_ERROR_STATUS_TYPE WHERE NAME = 'WARNING' AND DESCRIPTION = 'Transaccion que finaliza con advertencias' AND RCD_STATUS = '1');	END;
	BEGIN		DELETE FROM ESB_ERROR_STATUS_TYPE WHERE ID = (SELECT ID FROM ESB_ERROR_STATUS_TYPE WHERE NAME = 'ERROR' AND DESCRIPTION = 'Transaccion que finaliza con error' AND RCD_STATUS = '1');	END;
END;/COMMIT;
