SET ECHO ON
SET DEFINE OFF
SET SERVEROUTPUT ON
WHENEVER SQLERROR CONTINUE ROLLBACK

DECLARE

BEGIN

	BEGIN
		DELETE FROM ESB_ERROR_TREATMENT_TYPE WHERE ID = (SELECT ID FROM ESB_ERROR_TREATMENT_TYPE WHERE NAME = 'Mail' AND DESCRIPTION = 'Envio de Error por Mail.' AND RCD_STATUS = '1');
	END;

END;
/

COMMIT;

