SET ECHO ON
SET DEFINE OFF
SET SERVEROUTPUT ON
WHENEVER SQLERROR CONTINUE ROLLBACK

DECLARE

BEGIN

	BEGIN
		DELETE FROM ESB_CONSUMER_DETAILS_TYPE WHERE ID = (SELECT ID FROM ESB_CONSUMER_DETAILS_TYPE WHERE NAME = 'TRANSPORT' AND DESCRIPTION = 'Consumer Callback TRANSPORT');
	END;
	
	BEGIN		
		DELETE FROM ESB_CONSUMER_DETAILS_TYPE WHERE ID = (SELECT ID FROM ESB_CONSUMER_DETAILS_TYPE WHERE NAME = 'URL' AND DESCRIPTION = 'Consumer Callback URI');
	END;
	
	BEGIN		
		DELETE FROM ESB_CONSUMER_DETAILS_TYPE WHERE ID = (SELECT ID FROM ESB_CONSUMER_DETAILS_TYPE WHERE NAME = 'Mail' AND DESCRIPTION = 'Mail Address');
	END;

END;
/

COMMIT;
