SET ECHO ON
SET DEFINE OFF
SET SERVEROUTPUT ON
WHENEVER SQLERROR CONTINUE ROLLBACK

DECLARE

BEGIN

	BEGIN
		DELETE FROM ESB_CHECK_TYPE WHERE ID = (SELECT ID FROM ESB_CHECK_TYPE WHERE NAME = 'IDEMPOTENT' AND GRADE = '10' AND RCD_STATUS = '1');
	END;
	
	BEGIN
		DELETE FROM ESB_CHECK_TYPE WHERE ID = (SELECT ID FROM ESB_CHECK_TYPE WHERE NAME = 'RESULT' AND GRADE = '5' AND RCD_STATUS = '1');
	END;

END;
/

COMMIT;
