SET ECHO ON
SET DEFINE OFF
SET SERVEROUTPUT ON
WHENEVER SQLERROR CONTINUE ROLLBACK

DECLARE

BEGIN

	BEGIN
		DELETE FROM ESB_DEFAULT_CHECK WHERE ID = (SELECT ID FROM ESB_DEFAULT_CHECK WHERE TYPE = '1' AND NAME = 'ONGOING' AND GRADE = '100' AND RCD_STATUS = '1' AND ELAPSED_TIME = '0 0:1:0.0');
	END;
	
	BEGIN
		DELETE FROM ESB_DEFAULT_CHECK WHERE ID = (SELECT ID FROM ESB_DEFAULT_CHECK WHERE TYPE = '2' AND NAME = 'REJECT' AND GRADE = '0' AND RCD_STATUS = '1' AND ELAPSED_TIME = '0 0:0:0.0');
	END;
	
END;
/

COMMIT;
