SET ECHO ONSET DEFINE OFFSET SERVEROUTPUT ONWHENEVER SQLERROR CONTINUE ROLLBACKDECLAREBEGIN
	BEGIN		DELETE FROM ESB_CANONICAL_ERROR_TYPE WHERE TYPE = 'NEG' AND RCD_STATUS = '1';	END;
	BEGIN		DELETE FROM ESB_CANONICAL_ERROR_TYPE WHERE TYPE = 'DAT' AND RCD_STATUS = '1';	END;
	BEGIN		DELETE FROM ESB_CANONICAL_ERROR_TYPE WHERE TYPE = 'TEC' AND RCD_STATUS = '1';	END;
	BEGIN		DELETE FROM ESB_CANONICAL_ERROR_TYPE WHERE TYPE = 'SEG' AND RCD_STATUS = '1';	END;
	BEGIN		DELETE FROM ESB_CANONICAL_ERROR_TYPE WHERE TYPE = 'UNK' AND RCD_STATUS = '1';	END;
	BEGIN		DELETE FROM ESB_CANONICAL_ERROR_TYPE WHERE TYPE = 'FWNE' AND RCD_STATUS = '1';	END;
	BEGIN		DELETE FROM ESB_CANONICAL_ERROR_TYPE WHERE TYPE = 'FWDA' AND RCD_STATUS = '1';	END;
	BEGIN		DELETE FROM ESB_CANONICAL_ERROR_TYPE WHERE TYPE = 'FWTE' AND RCD_STATUS = '1';	END;
	BEGIN		DELETE FROM ESB_CANONICAL_ERROR_TYPE WHERE TYPE = 'FWSE' AND RCD_STATUS = '1';	END;
	BEGIN		DELETE FROM ESB_CANONICAL_ERROR_TYPE WHERE TYPE = 'FWUN' AND RCD_STATUS = '1';	END;
	BEGIN		DELETE FROM ESB_CANONICAL_ERROR_TYPE WHERE TYPE = 'FWCF' AND RCD_STATUS = '1';	END;	BEGIN		DELETE FROM ESB_CANONICAL_ERROR_TYPE WHERE TYPE = 'NCNE' AND RCD_STATUS = '1';	END;		BEGIN		DELETE FROM ESB_CANONICAL_ERROR_TYPE WHERE TYPE = 'NCDA' AND RCD_STATUS = '1';	END;		BEGIN		DELETE FROM ESB_CANONICAL_ERROR_TYPE WHERE TYPE = 'NCTE' AND RCD_STATUS = '1';	END;		BEGIN		DELETE FROM ESB_CANONICAL_ERROR_TYPE WHERE TYPE = 'NCSE' AND RCD_STATUS = '1';	END;		BEGIN		DELETE FROM ESB_CANONICAL_ERROR_TYPE WHERE TYPE = 'NCUN' AND RCD_STATUS = '1';	END;
END;/COMMIT;
