SET ECHO ON
SET DEFINE OFF
SET SERVEROUTPUT ON
WHENEVER SQLERROR CONTINUE ROLLBACK
DECLARE
BEGIN
BEGIN
DELETE FROM ESB_CONSUMER_CAP_DETAILS_TYPE WHERE ID = (SELECT ID FROM ESB_CONSUMER_CAP_DETAILS_TYPE WHERE NAME = 'TRANSPORT');
END;
BEGIN
DELETE FROM ESB_CONSUMER_CAP_DETAILS_TYPE WHERE ID = (SELECT ID FROM ESB_CONSUMER_CAP_DETAILS_TYPE WHERE NAME = 'CALLBACK_URL');
END;
END;
/
COMMIT;