SET ECHO ON
SET DEFINE OFF
SET SERVEROUTPUT ON
WHENEVER SQLERROR CONTINUE ROLLBACK

DECLARE

BEGIN

	BEGIN
		DELETE FROM ESB_CONFIG_PROPERTY WHERE ID = (SELECT ID FROM ESB_CONFIG_PROPERTY WHERE NAME = 'soapAction' AND DESCRIPTION = 'SOAPAction, para 1.1 o 1.2' AND RCD_STATUS = '1');
	END;
	
	BEGIN
		DELETE FROM ESB_CONFIG_PROPERTY WHERE ID = (SELECT ID FROM ESB_CONFIG_PROPERTY WHERE NAME = 'url' AND DESCRIPTION = 'URL for service' AND RCD_STATUS = '1');
	END;
	
	BEGIN
		DELETE FROM ESB_CONFIG_PROPERTY WHERE ID = (SELECT ID FROM ESB_CONFIG_PROPERTY WHERE NAME ='path' AND DESCRIPTION = 'path' AND RCD_STATUS = '1');
	END;
	
	BEGIN
		DELETE FROM ESB_CONFIG_PROPERTY WHERE ID = (SELECT ID FROM ESB_CONFIG_PROPERTY WHERE NAME = 'legalType' AND DESCRIPTION = 'legalType' AND RCD_STATUS = '1');
	END;
	
END;
/

COMMIT;
