SET ECHO ON
SET DEFINE OFF
SET SERVEROUTPUT ON
WHENEVER SQLERROR CONTINUE ROLLBACK

DECLARE

BEGIN

	BEGIN
		INSERT INTO ESB_SERVICE_DETAILS (ID,SERVICE_ID, DETAIL_TYPE_ID, DETAIL_CONTENT, RCD_STATUS)
	    VALUES (ESB_SERVICES_DETAILS_SEQ.NEXTVAL, 
	      (SELECT ID FROM ESB_SERVICE WHERE ESB_SERVICE.NAME = 'Consumer' AND ESB_SERVICE.CODE = '100'),
	      (SELECT ID FROM ESB_SERVICE_DETAILS_TYPE WHERE NAME = 'Endpoint'),
	      'http://172.17.216.67:8001/ES/Consumer/v1',
	      1
	    );
	END;
	
END;
/

COMMIT;

