SET ECHO ON
SET DEFINE OFF
SET SERVEROUTPUT ON
WHENEVER SQLERROR CONTINUE ROLLBACK

DECLARE

BEGIN

	BEGIN
		INSERT INTO ESB_CAPABILITY_DETAILS ( ID, CAPABILITY_ID, DETAIL_TYPE_ID, DETAIL_CONTENT, RCD_STATUS )
	    VALUES (ESB_CAPABILITY_DETAILS_SEQ.NEXTVAL,
	      (SELECT ESB_CAPABILITY.ID FROM ESB_SERVICE INNER JOIN ESB_CAPABILITY ON ESB_CAPABILITY.SERVICE_ID = ESB_SERVICE.ID WHERE ESB_SERVICE.NAME = 'Consumer' AND ESB_SERVICE.CODE = '100' AND ESB_CAPABILITY.CODE = '101' AND ESB_CAPABILITY.NAME = 'get'),
	      (SELECT ID FROM ESB_CAPABILITY_DETAILS_TYPE WHERE NAME = 'Action' ), --INSERTADO POR FRW
	      'http://www.entel.cl/EBM/Consumer/get/v1',
	      1
	    );
	END;
	
END;
/

COMMIT;

