SET ECHO ON
SET DEFINE OFF
SET SERVEROUTPUT ON
WHENEVER SQLERROR CONTINUE ROLLBACK

DECLARE

BEGIN

	BEGIN
		INSERT INTO ESB_ERROR_TREATMENT_PLAN (ID,THERAPY_ID,TREATMENT_ID,RCD_STATUS) VALUES (ESB_ERROR_TREATMENT_PLAN_SEQ.NEXTVAL,( SELECT ID FROM ESB_ERROR_THERAPY WHERE NAME = 'SALESFORCE'),( SELECT ID FROM ESB_ERROR_TREATMENT_TYPE WHERE NAME = 'Mail'),'1');
	END;

	BEGIN
		INSERT INTO ESB_ERROR_TREATMENT_PLAN (ID,THERAPY_ID,TREATMENT_ID,RCD_STATUS) VALUES (ESB_ERROR_TREATMENT_PLAN_SEQ.NEXTVAL,( SELECT ID FROM ESB_ERROR_THERAPY WHERE NAME = 'TERAPIA_1'),(SELECT ID FROM ESB_ERROR_TREATMENT_TYPE WHERE NAME='Retry'),  '1');
	END;
	
END;
/

COMMIT;
