SET ECHO ON
SET DEFINE OFF
SET SERVEROUTPUT ON
WHENEVER SQLERROR CONTINUE ROLLBACK

DECLARE

BEGIN

	BEGIN 
		INSERT INTO ESB_CONFIG_LIST (CONFIG_ID,PROPERTY_ID,VALUE,RCD_STATUS) VALUES (( SELECT ID FROM ESB_CONFIG WHERE NAME = 'CHL-SALESFORCE-CRM_ClientObtain_HTTPSOAP12'),( SELECT ID FROM ESB_CONFIG_PROPERTY WHERE NAME = 'url'),'http://172.17.201.86:8501/salesforce/clientObtain','1');
	END;
	
	BEGIN
		INSERT INTO ESB_CONFIG_LIST (CONFIG_ID,PROPERTY_ID,VALUE,RCD_STATUS) VALUES (( SELECT ID FROM ESB_CONFIG WHERE NAME = 'CHL-SALESFORCE-CRM_ClientObtain_HTTPSOAP12'),( SELECT ID FROM ESB_CONFIG_PROPERTY WHERE NAME = 'soapAction'),'""','1');
	END;

	BEGIN 
		INSERT INTO ESB_CONFIG_LIST (CONFIG_ID,PROPERTY_ID,VALUE,RCD_STATUS) VALUES (( SELECT ID FROM ESB_CONFIG WHERE NAME = 'CHL-SALESFORCE-CRM_ClientDelete_HTTPSOAP12'),( SELECT ID FROM ESB_CONFIG_PROPERTY WHERE NAME = 'url'),'http://172.17.201.86:8502/salesforce/clientDelete','1');
	END;
	
	BEGIN
		INSERT INTO ESB_CONFIG_LIST (CONFIG_ID,PROPERTY_ID,VALUE,RCD_STATUS) VALUES (( SELECT ID FROM ESB_CONFIG WHERE NAME = 'CHL-SALESFORCE-CRM_ClientDelete_HTTPSOAP12'),( SELECT ID FROM ESB_CONFIG_PROPERTY WHERE NAME = 'soapAction'),'""','1');
	END;	
	
	BEGIN
		INSERT INTO ESB_CONFIG_LIST (CONFIG_ID,PROPERTY_ID,VALUE,RCD_STATUS) VALUES (( SELECT ID FROM ESB_CONFIG WHERE NAME = 'INT-AS400-CLI_ClientDelete_HTTPSOAP11'),( SELECT ID FROM ESB_CONFIG_PROPERTY WHERE NAME = 'url'),'http://172.17.201.86:8503/as400/clientDelete','1');
	END;
	
	BEGIN
		INSERT INTO ESB_CONFIG_LIST (CONFIG_ID,PROPERTY_ID,VALUE,RCD_STATUS) VALUES (( SELECT ID FROM ESB_CONFIG WHERE NAME = 'INT-AS400-CLI_ClientDelete_HTTPSOAP11'),( SELECT ID FROM ESB_CONFIG_PROPERTY WHERE NAME = 'soapAction'),'"http://www.entel.as400.com/client"','1');
	END;	

END;
/

COMMIT;
