SET ECHO ON
SET DEFINE OFF
SET SERVEROUTPUT ON
WHENEVER SQLERROR CONTINUE ROLLBACK

DECLARE

BEGIN

	BEGIN
		INSERT INTO ESB_ENDPOINT (OPERATION_ID,TRANSPORT_ID,INSTANCE,CONFIG_ID,RCD_STATUS) VALUES ((SELECT O.ID FROM ESB_SYSTEM_API_OPERATION O INNER JOIN ESB_SYSTEM_API A ON O.SYSTEM_API_ID = A.ID WHERE O.NAME = 'ClientDelete' AND A.CODE = 'CHL-SALESFORCE-CRM'),( SELECT ID FROM ESB_ENDPOINT_TRANSPORT WHERE NAME = 'HTTPSOAP12'),null,( SELECT ID FROM ESB_CONFIG WHERE NAME = 'CHL-SALESFORCE-CRM_ClientDelete_HTTPSOAP12'),'1');
	END;
	
	BEGIN
		INSERT INTO ESB_ENDPOINT (OPERATION_ID,TRANSPORT_ID,INSTANCE,CONFIG_ID,RCD_STATUS) VALUES ((SELECT O.ID FROM ESB_SYSTEM_API_OPERATION O INNER JOIN ESB_SYSTEM_API A ON O.SYSTEM_API_ID = A.ID WHERE O.NAME = 'ClientObtain' AND A.CODE = 'CHL-SALESFORCE-CRM'),( SELECT ID FROM ESB_ENDPOINT_TRANSPORT WHERE NAME = 'HTTPSOAP12'),null,( SELECT ID FROM ESB_CONFIG WHERE NAME = 'CHL-SALESFORCE-CRM_ClientObtain_HTTPSOAP12'),'1');
	END;
	
	BEGIN
		INSERT INTO ESB_ENDPOINT (OPERATION_ID,TRANSPORT_ID,INSTANCE,CONFIG_ID,RCD_STATUS) VALUES ((SELECT O.ID FROM ESB_SYSTEM_API_OPERATION O INNER JOIN ESB_SYSTEM_API A ON O.SYSTEM_API_ID = A.ID WHERE O.NAME = 'UPD-CLI-DATA' AND A.CODE = 'CHL-SALESFORCE-CRM'),( SELECT ID FROM ESB_ENDPOINT_TRANSPORT WHERE NAME = 'JMS'),null,( SELECT ID FROM ESB_CONFIG WHERE NAME = 'CHL-SALESFORCE-CRM_UPD_CLI_DATA_JMS'),'1');
	END;
	
	BEGIN
		INSERT INTO ESB_ENDPOINT (OPERATION_ID,TRANSPORT_ID,INSTANCE,CONFIG_ID,RCD_STATUS) VALUES ((SELECT O.ID FROM ESB_SYSTEM_API_OPERATION O INNER JOIN ESB_SYSTEM_API A ON O.SYSTEM_API_ID = A.ID WHERE O.NAME = 'ClientDelete' AND A.CODE = 'INT-AS400-CLI'),( SELECT ID FROM ESB_ENDPOINT_TRANSPORT WHERE NAME = 'HTTPSOAP11'),null,( SELECT ID FROM ESB_CONFIG WHERE NAME = 'INT-AS400-CLI_ClientDelete_HTTPSOAP11'),'1');
	END;
	
END;
/

COMMIT;

