SET ECHO ONSET DEFINE OFFSET SERVEROUTPUT ONWHENEVER SQLERROR CONTINUE ROLLBACKDECLAREvRes NUMBER;BEGIN
	BEGIN			INSERT INTO ESB_CAPABILITY (ID,SERVICE_ID,CODE,NAME,RCD_STATUS) VALUES (ESB_CAPABILITY_SEQ.NEXTVAL,( SELECT ID FROM ESB_SERVICE WHERE CODE = '100'),'104','upd','1');	END;
	BEGIN			INSERT INTO ESB_CAPABILITY (ID,SERVICE_ID,CODE,NAME,RCD_STATUS) VALUES (ESB_CAPABILITY_SEQ.NEXTVAL,( SELECT ID FROM ESB_SERVICE WHERE CODE = '100'),'103','del','1');	END;
	BEGIN			INSERT INTO ESB_CAPABILITY (ID,SERVICE_ID,CODE,NAME,RCD_STATUS) VALUES (ESB_CAPABILITY_SEQ.NEXTVAL,( SELECT ID FROM ESB_SERVICE WHERE CODE = '100'),'101','get','1');	END;
	BEGIN			INSERT INTO ESB_CAPABILITY (ID,SERVICE_ID,CODE,NAME,RCD_STATUS) VALUES (ESB_CAPABILITY_SEQ.NEXTVAL,( SELECT ID FROM ESB_SERVICE WHERE CODE = '100'),'102','put','1');	END;	END;/COMMIT;
