SPOOL salida_inserts_all_tables.txt
@INSERT_ESB_CANONICAL_ERROR.sql
@INSERT_ESB_SERVICE.sql
@INSERT_ESB_SERVICE_DETAILS.sql
@INSERT_ESB_CAPABILITY.sql
@INSERT_ESB_CAPABILITY_DETAILS.sql
@INSERT_ESB_CAPABILITY_CHECK.sql
@INSERT_ESB_CDM_ENTITY.sql
@INSERT_ESB_CDM_FIELD.sql
@INSERT_ESB_CHANNEL.sql
@INSERT_ESB_CHECK_CONFIG.sql
@INSERT_ESB_CONFIG.sql
@INSERT_ESB_CONFIG_LIST.sql
@INSERT_ESB_PARAMETER.sql
@INSERT_ESB_SYSTEM.sql
@INSERT_ESB_SYSTEM_API.sql
@INSERT_ESB_SYSTEM_API_OPERATION.sql
@INSERT_ESB_ENDPOINT.sql
@INSERT_ESB_CONSUMER.sql
@INSERT_ESB_CONSUMER_DETAILS.sql
@INSERT_ESB_ERROR_THERAPY.sql
@INSERT_ESB_ERROR_TREATMENT_PLAN.sql
@INSERT_ESB_ERROR_DIAGNOSIS.sql
@INSERT_ESB_ERROR_MAPPING.sql
@INSERT_ESB_MAPPING.sql
@INSERT_ESB_RETRYMANAGER_CONFIG.sql
SPOOL OFF;