SET ECHO ON
SET DEFINE OFF
SET SERVEROUTPUT ON
WHENEVER SQLERROR CONTINUE ROLLBACK

DECLARE

BEGIN

	BEGIN
		INSERT INTO ESB_PARAMETER (KEY,VALUE,RCD_STATUS) VALUES ('Logger.log.IsEnabled.100.Consumer.put','1','1');
	END;
	
	BEGIN
		INSERT INTO ESB_PARAMETER (KEY,VALUE,RCD_STATUS) VALUES ('Logger.error.IsEnabled.100.Consumer.put','1','1');
	END;

	BEGIN
		INSERT INTO ESB_PARAMETER (KEY,VALUE,RCD_STATUS) VALUES ('Logger.log.IsEnabled.100.Consumer.del','1','1');
	END;
	
	BEGIN
		INSERT INTO ESB_PARAMETER (KEY,VALUE,RCD_STATUS) VALUES ('Logger.error.IsEnabled.100.Consumer.del','1','1');
	END;

	BEGIN
		INSERT INTO ESB_PARAMETER (KEY,VALUE,RCD_STATUS) VALUES ('Logger.log.IsEnabled.100.Consumer.get','1','1');
	END;
	
	BEGIN
		INSERT INTO ESB_PARAMETER (KEY,VALUE,RCD_STATUS) VALUES ('Logger.error.IsEnabled.100.Consumer.get','1','1');
	END;

	BEGIN
		INSERT INTO ESB_PARAMETER (KEY,VALUE,RCD_STATUS) VALUES ('Logger.log.IsEnabled.100.Consumer.upd','1','1');
	END;

	BEGIN
		INSERT INTO ESB_PARAMETER (KEY,VALUE,RCD_STATUS) VALUES ('Logger.error.IsEnabled.100.Consumer.upd','1','1');
	END;
	
	BEGIN
		INSERT INTO ESB_PARAMETER (KEY,VALUE,RCD_STATUS) VALUES ('CHL-SALESFORCE-CRM_UPD-CLI-DATA_RA.VerDigit.1000','0','1');
	END;
	
	BEGIN
		INSERT INTO ESB_PARAMETER (KEY,VALUE,RCD_STATUS) VALUES ('CHL-SALESFORCE-CRM_UPD-CLI-DATA_RA.VerDigit.2000','1','1');
	END;
	
	BEGIN
		INSERT INTO ESB_PARAMETER (KEY,VALUE,RCD_STATUS) VALUES ('get_Consumer_OH.ConsumerType','National','1');
	END;
	
	BEGIN
		INSERT INTO ESB_PARAMETER (KEY, RCD_STATUS) VALUES ('unassigned', '1');
	END;

	BEGIN
		INSERT INTO ESB_PARAMETER (KEY,VALUE,RCD_STATUS) VALUES ('SourceError.ErrorDesc.CR0002.del.00','Transaccion Exitosa','1');
	END;

	BEGIN
		INSERT INTO ESB_PARAMETER (KEY,VALUE,RCD_STATUS) VALUES ('SourceError.ErrorDesc.CR0002.del.999','Error sin traduccion Definida','1');
	END;


	BEGIN
		INSERT INTO ESB_PARAMETER (KEY,VALUE,RCD_STATUS) VALUES ('SourceError.ErrorDesc.CR0002.del.9161','Error Funcional del Legado.','1');
	END;

END;
/

COMMIT;
