SET ECHO ON
SET DEFINE OFF
SET SERVEROUTPUT ON
WHENEVER SQLERROR CONTINUE ROLLBACK

DECLARE

BEGIN

	BEGIN
		INSERT INTO ESB_CONFIG (ID,NAME,RCD_STATUS) VALUES (ESB_CONFIG_SEQ.NEXTVAL,'CHL-SALESFORCE-CRM_ClientObtain_HTTPSOAP12','1');
	END;
	
	BEGIN
		INSERT INTO ESB_CONFIG (ID,NAME,RCD_STATUS) VALUES (ESB_CONFIG_SEQ.NEXTVAL,'CHL-SALESFORCE-CRM_ClientDelete_HTTPSOAP12','1');
	END;
	
	BEGIN
		INSERT INTO ESB_CONFIG (ID,NAME,RCD_STATUS) VALUES (ESB_CONFIG_SEQ.NEXTVAL,'CHL-SALESFORCE-CRM_UPD_CLI_DATA_JMS','1');
	END;

	BEGIN
		INSERT INTO ESB_CONFIG (ID,NAME,RCD_STATUS) VALUES (ESB_CONFIG_SEQ.NEXTVAL,'INT-AS400-CLI_ClientDelete_HTTPSOAP11','1');
	END;
	
END;
/

COMMIT;

