SET ECHO ON
SET DEFINE OFF
SET SERVEROUTPUT ON
WHENEVER SQLERROR CONTINUE ROLLBACK

DECLARE

BEGIN

	BEGIN
		INSERT INTO ESB_CHECK_CONFIG (CAP_CHK_ID,CHECK_TYPE_ID,ELAPSED_TIME,RCD_STATUS) VALUES ((SELECT ID FROM ESB_CAPABILITY_CHECK WHERE CAPABILITY_ID = ( SELECT ID FROM ESB_CAPABILITY WHERE CODE = '103')),( SELECT ID FROM ESB_CHECK_TYPE WHERE NAME = 'IDEMPOTENT'),'0 0:1:0.0','1');
	END;
	
	BEGIN
		INSERT INTO ESB_CHECK_CONFIG (CAP_CHK_ID,CHECK_TYPE_ID,ELAPSED_TIME,RCD_STATUS) VALUES ((SELECT ID FROM ESB_CAPABILITY_CHECK WHERE CAPABILITY_ID = ( SELECT ID FROM ESB_CAPABILITY WHERE CODE = '103')),( SELECT ID FROM ESB_CHECK_TYPE WHERE NAME = 'RESULT'),'0 0:1:30.0','1');
	END;

END;
/

COMMIT;
