SET ECHO ON
SET DEFINE OFF
SET SERVEROUTPUT ON
WHENEVER SQLERROR CONTINUE ROLLBACK

DECLARE

BEGIN

	BEGIN
		Insert into ESB_ERROR_MAPPING (ID,ERROR_SOURCE,MODULE,SUB_MODULE,RAW_CODE,RAW_DESCRIPTION,CAN_ERR_ID,STATUS_ID,RCD_STATUS) values (ESB_ERROR_MAPPING_SEQ.NEXTVAL,( SELECT ID FROM ESB_SYSTEM WHERE CODE = 'CHL-SALESFORCE'),'CHL-SALESFORCE-CRM','ClientObtain','1','Transaccion Fuera de Horario',( SELECT ID FROM ESB_CANONICAL_ERROR WHERE CODE = '161'),( SELECT ID FROM ESB_ERROR_STATUS_TYPE WHERE NAME = 'ERROR'),'1');
	END;
		
	BEGIN
		Insert into ESB_ERROR_MAPPING (ID,ERROR_SOURCE,MODULE,SUB_MODULE,RAW_CODE,RAW_DESCRIPTION,CAN_ERR_ID,STATUS_ID,RCD_STATUS) values (ESB_ERROR_MAPPING_SEQ.NEXTVAL,( SELECT ID FROM ESB_SYSTEM WHERE CODE = 'CHL-SALESFORCE'),'CHL-SALESFORCE-CRM','UPD_CLI_DATA','1','ConsumerID no encontrado',( SELECT ID FROM ESB_CANONICAL_ERROR WHERE CODE = '90000'),( SELECT ID FROM ESB_ERROR_STATUS_TYPE WHERE NAME = 'ERROR'),'1');
	END;	
		
	BEGIN	
		Insert into ESB_ERROR_MAPPING (ID,ERROR_SOURCE,MODULE,SUB_MODULE,RAW_CODE,RAW_DESCRIPTION,CAN_ERR_ID,STATUS_ID,RCD_STATUS) values (ESB_ERROR_MAPPING_SEQ.NEXTVAL,( SELECT ID FROM ESB_SYSTEM WHERE CODE = 'CHL-SALESFORCE'),'CHL-SALESFORCE-CRM','ClientDelete','1','Transaccion Fuera de Horario',( SELECT ID FROM ESB_CANONICAL_ERROR WHERE CODE = '161'),( SELECT ID FROM ESB_ERROR_STATUS_TYPE WHERE NAME = 'ERROR'),'1');
	END;

	BEGIN	
		Insert into ESB_ERROR_MAPPING (ID,ERROR_SOURCE,MODULE,SUB_MODULE,RAW_CODE,RAW_DESCRIPTION,CAN_ERR_ID,STATUS_ID,RCD_STATUS) values (ESB_ERROR_MAPPING_SEQ.NEXTVAL,( SELECT ID FROM ESB_SYSTEM WHERE CODE = 'INT-AS400'),'INT-AS400-CLI','ClientDelete','1','Cliente Inexistente',( SELECT ID FROM ESB_CANONICAL_ERROR WHERE CODE = '90000'),( SELECT ID FROM ESB_ERROR_STATUS_TYPE WHERE NAME = 'ERROR'),'1');
	END;
	
	BEGIN	
		Insert into ESB_ERROR_MAPPING (ID,ERROR_SOURCE,MODULE,SUB_MODULE,RAW_CODE,RAW_DESCRIPTION,CAN_ERR_ID,STATUS_ID,RCD_STATUS) values (ESB_ERROR_MAPPING_SEQ.NEXTVAL,( SELECT ID FROM ESB_SYSTEM WHERE CODE = 'CHL-SALESFORCE'),'','','','',( SELECT ID FROM ESB_CANONICAL_ERROR WHERE CODE = '350'),( SELECT ID FROM ESB_ERROR_STATUS_TYPE WHERE NAME = 'ERROR'),'1');
	END;
	
	BEGIN	
		Insert into ESB_ERROR_MAPPING (ID,ERROR_SOURCE,MODULE,SUB_MODULE,RAW_CODE,RAW_DESCRIPTION,CAN_ERR_ID,STATUS_ID,RCD_STATUS) values (ESB_ERROR_MAPPING_SEQ.NEXTVAL,( SELECT ID FROM ESB_SYSTEM WHERE CODE = 'INT-AS400'),'','','','',( SELECT ID FROM ESB_CANONICAL_ERROR WHERE CODE = '351'),( SELECT ID FROM ESB_ERROR_STATUS_TYPE WHERE NAME = 'ERROR'),'1');
	END;
	
	BEGIN
		Insert into ESB_ERROR_MAPPING (ID,ERROR_SOURCE,MODULE,SUB_MODULE,RAW_CODE,RAW_DESCRIPTION,CAN_ERR_ID,STATUS_ID,RCD_STATUS) values (ESB_ERROR_MAPPING_SEQ.NEXTVAL,( SELECT ID FROM ESB_SYSTEM WHERE CODE = 'CHL-SALESFORCE'),'CHL-SALESFORCE-CRM','ClientObtain','0','',( SELECT ID FROM ESB_CANONICAL_ERROR WHERE CODE = '0'),( SELECT ID FROM ESB_ERROR_STATUS_TYPE WHERE NAME = 'OK'),'1');
	END;
		
	BEGIN
		Insert into ESB_ERROR_MAPPING (ID,ERROR_SOURCE,MODULE,SUB_MODULE,RAW_CODE,RAW_DESCRIPTION,CAN_ERR_ID,STATUS_ID,RCD_STATUS) values (ESB_ERROR_MAPPING_SEQ.NEXTVAL,( SELECT ID FROM ESB_SYSTEM WHERE CODE = 'CHL-SALESFORCE'),'CHL-SALESFORCE-CRM','UPD_CLI_DATA','0','C',( SELECT ID FROM ESB_CANONICAL_ERROR WHERE CODE = '0'),( SELECT ID FROM ESB_ERROR_STATUS_TYPE WHERE NAME = 'OK'),'1');
	END;	
		
	BEGIN	
		Insert into ESB_ERROR_MAPPING (ID,ERROR_SOURCE,MODULE,SUB_MODULE,RAW_CODE,RAW_DESCRIPTION,CAN_ERR_ID,STATUS_ID,RCD_STATUS) values (ESB_ERROR_MAPPING_SEQ.NEXTVAL,( SELECT ID FROM ESB_SYSTEM WHERE CODE = 'CHL-SALESFORCE'),'CHL-SALESFORCE-CRM','ClientDelete','0','',( SELECT ID FROM ESB_CANONICAL_ERROR WHERE CODE = '0'),( SELECT ID FROM ESB_ERROR_STATUS_TYPE WHERE NAME = 'OK'),'1');
	END;

	BEGIN	
		Insert into ESB_ERROR_MAPPING (ID,ERROR_SOURCE,MODULE,SUB_MODULE,RAW_CODE,RAW_DESCRIPTION,CAN_ERR_ID,STATUS_ID,RCD_STATUS) values (ESB_ERROR_MAPPING_SEQ.NEXTVAL,( SELECT ID FROM ESB_SYSTEM WHERE CODE = 'INT-AS400'),'INT-AS400-CLI','ClientDelete','0','',( SELECT ID FROM ESB_CANONICAL_ERROR WHERE CODE = '0'),( SELECT ID FROM ESB_ERROR_STATUS_TYPE WHERE NAME = 'OK'),'1');
	END;

END;
/

COMMIT;
