SET ECHO ON
SET DEFINE OFF
SET SERVEROUTPUT ON
WHENEVER SQLERROR CONTINUE ROLLBACK

DECLARE

BEGIN

	BEGIN
		INSERT INTO ESB_ERROR_THERAPY (ID,NAME,RCD_STATUS) VALUES (ESB_ERROR_THERAPY_SEQ.NEXTVAL,'SALESFORCE','1');
	END;

	BEGIN
		INSERT INTO ESB_ERROR_THERAPY (ID,NAME,RCD_STATUS) VALUES (ESB_ERROR_THERAPY_SEQ.NEXTVAL,'TERAPIA_1', 1);
	END;	
END;
/

COMMIT;
