SET ECHO ON
SET DEFINE OFF
SET SERVEROUTPUT ON
WHENEVER SQLERROR CONTINUE ROLLBACK

DECLARE

BEGIN

	BEGIN
		INSERT INTO ESB_CONSUMER_DETAILS (ID,CONSUMER_ID,DETAIL_TYPE_ID, DETAIL_CONTENT) VALUES (ESB_CONSUMER_DETAILS_SEQ.NEXTVAL,( SELECT ID FROM ESB_CONSUMER WHERE SYSCODE = ( SELECT ID FROM ESB_SYSTEM WHERE CODE = 'CHL-SALESFORCE') AND COUNTRY_ID = ( SELECT ID FROM ESB_COUNTRY WHERE CODE = 'CHL') AND ENT_CODE = ( SELECT ID FROM ESB_ENTERPRISE WHERE CODE = 'ENTEL')),( SELECT ID FROM ESB_CONSUMER_DETAILS_TYPE WHERE NAME = 'URL'), 'HTTP://172.17.201.86:7003/Dummmy_GetConsumerCallback');
	END;
		
	BEGIN		
		INSERT INTO ESB_CONSUMER_DETAILS (ID,CONSUMER_ID,DETAIL_TYPE_ID, DETAIL_CONTENT) VALUES (ESB_CONSUMER_DETAILS_SEQ.NEXTVAL,( SELECT ID FROM ESB_CONSUMER WHERE SYSCODE = ( SELECT ID FROM ESB_SYSTEM WHERE CODE = 'CHL-SALESFORCE') AND COUNTRY_ID = ( SELECT ID FROM ESB_COUNTRY WHERE CODE = 'CHL') AND ENT_CODE = ( SELECT ID FROM ESB_ENTERPRISE WHERE CODE = 'ENTEL')),( SELECT ID FROM ESB_CONSUMER_DETAILS_TYPE WHERE NAME = 'TRANSPORT'), 'HTTP');
	END;
	
	BEGIN		
		INSERT INTO ESB_CONSUMER_DETAILS (ID,CONSUMER_ID,DETAIL_TYPE_ID, DETAIL_CONTENT) VALUES (ESB_CONSUMER_DETAILS_SEQ.NEXTVAL,( SELECT ID FROM ESB_CONSUMER WHERE SYSCODE = ( SELECT ID FROM ESB_SYSTEM WHERE CODE = 'CHL-SALESFORCE') AND COUNTRY_ID = ( SELECT ID FROM ESB_COUNTRY WHERE CODE = 'CHL') AND ENT_CODE = ( SELECT ID FROM ESB_ENTERPRISE WHERE CODE = 'ENTEL')),( SELECT ID FROM ESB_CONSUMER_DETAILS_TYPE WHERE NAME = 'Mail'), 'facundoferro@gmail.com');
	END;
	
	BEGIN		
		INSERT INTO ESB_CONSUMER_DETAILS (ID,CONSUMER_ID,DETAIL_TYPE_ID, DETAIL_CONTENT) VALUES (ESB_CONSUMER_DETAILS_SEQ.NEXTVAL,( SELECT ID FROM ESB_CONSUMER WHERE SYSCODE = ( SELECT ID FROM ESB_SYSTEM WHERE CODE = 'CHL-SALESFORCE') AND COUNTRY_ID = ( SELECT ID FROM ESB_COUNTRY WHERE CODE = 'CHL') AND ENT_CODE = ( SELECT ID FROM ESB_ENTERPRISE WHERE CODE = 'ENTEL')),( SELECT ID FROM ESB_CONSUMER_DETAILS_TYPE WHERE NAME = 'Mail'), 'gemny.ibarra@globallogic.com');
	END;
	
	BEGIN		
		INSERT INTO ESB_CONSUMER_DETAILS (ID,CONSUMER_ID,DETAIL_TYPE_ID, DETAIL_CONTENT) VALUES (ESB_CONSUMER_DETAILS_SEQ.NEXTVAL,( SELECT ID FROM ESB_CONSUMER WHERE SYSCODE = ( SELECT ID FROM ESB_SYSTEM WHERE CODE = 'CHL-SALESFORCE') AND COUNTRY_ID = ( SELECT ID FROM ESB_COUNTRY WHERE CODE = 'CHL') AND ENT_CODE = ( SELECT ID FROM ESB_ENTERPRISE WHERE CODE = 'ENTEL')),( SELECT ID FROM ESB_CONSUMER_DETAILS_TYPE WHERE NAME = 'Mail'), 'sole.alfonso@globallogic.com');
	END;
	
	BEGIN		
		INSERT INTO ESB_CONSUMER_DETAILS (ID,CONSUMER_ID,DETAIL_TYPE_ID, DETAIL_CONTENT) VALUES (ESB_CONSUMER_DETAILS_SEQ.NEXTVAL,( SELECT ID FROM ESB_CONSUMER WHERE SYSCODE = ( SELECT ID FROM ESB_SYSTEM WHERE CODE = 'CHL-SALESFORCE') AND COUNTRY_ID = ( SELECT ID FROM ESB_COUNTRY WHERE CODE = 'CHL') AND ENT_CODE = ( SELECT ID FROM ESB_ENTERPRISE WHERE CODE = 'ENTEL')),( SELECT ID FROM ESB_CONSUMER_DETAILS_TYPE WHERE NAME = 'Mail'), 'mario.mesaglio@globallogic.com');
	END;
	
	BEGIN		
		INSERT INTO ESB_CONSUMER_DETAILS (ID,CONSUMER_ID,DETAIL_TYPE_ID, DETAIL_CONTENT) VALUES (ESB_CONSUMER_DETAILS_SEQ.NEXTVAL,( SELECT ID FROM ESB_CONSUMER WHERE SYSCODE = ( SELECT ID FROM ESB_SYSTEM WHERE CODE = 'CHL-SALESFORCE') AND COUNTRY_ID = ( SELECT ID FROM ESB_COUNTRY WHERE CODE = 'CHL') AND ENT_CODE = ( SELECT ID FROM ESB_ENTERPRISE WHERE CODE = 'ENTEL')),( SELECT ID FROM ESB_CONSUMER_DETAILS_TYPE WHERE NAME = 'Mail'), 'matias.gonsalves@globallogic.com');
	END;	
	
END;
/

COMMIT;
