SET ECHO ON
SET DEFINE OFF
SET SERVEROUTPUT ON
WHENEVER SQLERROR CONTINUE ROLLBACK

DECLARE

BEGIN

	BEGIN
		DELETE FROM ESB_SERVICE_DETAILS
		WHERE SERVICE_ID = (SELECT ID FROM ESB_SERVICE WHERE ESB_SERVICE.NAME = 'Consumer' AND ESB_SERVICE.CODE = '100') AND 
				DETAIL_TYPE_ID = (SELECT ID FROM ESB_SERVICE_DETAILS_TYPE WHERE NAME = 'Endpoint');
	END;
	
END;
/

COMMIT;

