SET ECHO ON
SET DEFINE OFF
SET SERVEROUTPUT ON
WHENEVER SQLERROR CONTINUE ROLLBACK

DECLARE

BEGIN

	BEGIN
		DELETE FROM  ESB_ERROR_TREATMENT_PLAN WHERE ID = (SELECT ID FROM ESB_ERROR_TREATMENT_PLAN WHERE THERAPY_ID = ( SELECT ID FROM ESB_ERROR_THERAPY WHERE NAME = 'SALESFORCE') AND TREATMENT_ID = ( SELECT ID FROM ESB_ERROR_TREATMENT_TYPE WHERE NAME = 'Mail') AND RCD_STATUS = '1');
	END;

	BEGIN
		DELETE FROM ESB_ERROR_TREATMENT_PLAN 
		WHERE ESB_ERROR_TREATMENT_PLAN.THERAPY_ID = (SELECT ESB_ERROR_THERAPY.ID FROM ESB_ERROR_THERAPY WHERE NAME = 'TERAPIA_1' ) AND 
			  ESB_ERROR_TREATMENT_PLAN.TREATMENT_ID = (SELECT ESB_ERROR_TREATMENT_TYPE.ID FROM ESB_ERROR_TREATMENT_TYPE WHERE NAME='Retry');
	END;
	
END;
/

COMMIT;