SET ECHO ON
SET DEFINE OFF
SET SERVEROUTPUT ON
WHENEVER SQLERROR CONTINUE ROLLBACK

DECLARE

BEGIN

	BEGIN
		DELETE FROM  ESB_CAPABILITY WHERE ID = (SELECT ID FROM ESB_CAPABILITY WHERE SERVICE_ID = ( SELECT ID FROM ESB_SERVICE WHERE CODE = '100') AND CODE = '104' AND NAME = 'upd' AND RCD_STATUS ='1');
	END;
	
	BEGIN
		DELETE FROM  ESB_CAPABILITY WHERE ID = (SELECT ID FROM ESB_CAPABILITY WHERE SERVICE_ID = ( SELECT ID FROM ESB_SERVICE WHERE CODE = '100') AND CODE = '103' AND NAME = 'del' AND RCD_STATUS='1');
	END;
	
	BEGIN
		DELETE FROM  ESB_CAPABILITY WHERE ID = (SELECT ID FROM ESB_CAPABILITY WHERE SERVICE_ID = ( SELECT ID FROM ESB_SERVICE WHERE CODE = '100') AND CODE = '101' AND NAME = 'get' AND RCD_STATUS='1');
	END;
	
	BEGIN
		DELETE FROM  ESB_CAPABILITY WHERE ID = (SELECT ID FROM ESB_CAPABILITY WHERE SERVICE_ID = ( SELECT ID FROM ESB_SERVICE WHERE CODE = '100') AND CODE = '102' AND NAME = 'put' AND RCD_STATUS='1');
	END;
	
END;
/

COMMIT;