SET ECHO ON
SET DEFINE OFF
SET SERVEROUTPUT ON
WHENEVER SQLERROR CONTINUE ROLLBACK

DECLARE

BEGIN

	BEGIN
		DELETE FROM  ESB_PARAMETER WHERE KEY = 'Logger.error.IsEnabled.100.Consumer.put' AND VALUE = '1' AND RCD_STATUS = '1';
	END;
	
	BEGIN
		DELETE FROM  ESB_PARAMETER WHERE KEY = 'Logger.error.IsEnabled.100.Consumer.del' AND VALUE = '1' AND RCD_STATUS = '1';
	END;
	
	BEGIN
		DELETE FROM  ESB_PARAMETER WHERE KEY = 'Logger.error.IsEnabled.100.Consumer.get' AND VALUE = '1' AND RCD_STATUS = '1';
	END;
	
	BEGIN
		DELETE FROM  ESB_PARAMETER WHERE KEY = 'Logger.error.IsEnabled.100.Consumer.upd' AND VALUE = '1' AND RCD_STATUS = '1';
	END;
	
	BEGIN
		DELETE FROM  ESB_PARAMETER WHERE KEY = 'Logger.log.IsEnabled.100.Consumer.put' AND VALUE = '1' AND RCD_STATUS = '1';
	END;
	
	BEGIN
		DELETE FROM  ESB_PARAMETER WHERE KEY = 'Logger.log.IsEnabled.100.Consumer.del' AND VALUE = '1' AND RCD_STATUS = '1';
	END;
	
	BEGIN
		DELETE FROM  ESB_PARAMETER WHERE KEY = 'Logger.log.IsEnabled.100.Consumer.get' AND VALUE = '1' AND RCD_STATUS = '1';
	END;
	
	BEGIN
		DELETE FROM  ESB_PARAMETER WHERE KEY = 'Logger.log.IsEnabled.100.Consumer.upd' AND VALUE = '1' AND RCD_STATUS = '1';
	END;
	
	BEGIN
		DELETE FROM  ESB_PARAMETER WHERE KEY = 'SALESFORCE_CRM_UPD-CLI-DATA_RA.VerDigit.1000' AND VALUE = '0' AND RCD_STATUS = '1';
	END;
	
	BEGIN
		DELETE FROM  ESB_PARAMETER WHERE KEY = 'SALESFORCE_CRM_UPD-CLI-DATA_RA.VerDigit.2000' AND VALUE = '1' AND RCD_STATUS = '1';
	END;
	
	BEGIN
		DELETE FROM  ESB_PARAMETER WHERE KEY = 'get_Consumer_OH.ConsumerType' AND VALUE = 'National' AND RCD_STATUS = '1';
	END;
	
	BEGIN
		DELETE FROM  ESB_PARAMETER WHERE KEY = 'unassigned' AND RCD_STATUS = '1';
	END;

	BEGIN
		DELETE FROM  ESB_PARAMETER WHERE KEY = 'SourceError.ErrorDesc.CR0002.del.00' AND VALUE = 'Transaccion Exitosa' AND RCD_STATUS = '1';
	END;

	BEGIN
		DELETE FROM  ESB_PARAMETER WHERE KEY = 'SourceError.ErrorDesc.CR0002.del.9161' AND VALUE = 'Error Funcional del Legado.' AND RCD_STATUS = '1';
	END;

	BEGIN
		DELETE FROM  ESB_PARAMETER WHERE KEY = 'SourceError.ErrorDesc.CR0002.del.999' AND VALUE = 'Error sin traduccion Definida' AND RCD_STATUS = '1';
	END;

		
END;
/

COMMIT;