SET ECHO ON
SET DEFINE OFF
SET SERVEROUTPUT ON
WHENEVER SQLERROR CONTINUE ROLLBACK

DECLARE

BEGIN

	BEGIN
		DELETE FROM  ESB_CDM_ENTITY WHERE ID = (SELECT ID FROM ESB_CDM_ENTITY WHERE NAME = 'Client' AND MAJ_VERSION = '1' AND DESCRIPTION = 'Client' AND RCD_STATUS = '1');
	END;

	BEGIN
		DELETE FROM  ESB_CDM_ENTITY WHERE ID = (SELECT ID FROM ESB_CDM_ENTITY WHERE NAME = 'CanonicalError' AND MAJ_VERSION = '1' AND DESCRIPTION = 'CanonicalError' AND RCD_STATUS = '1');
	END;
END;
/

COMMIT;