SET ECHO ON
SET DEFINE OFF
SET SERVEROUTPUT ON
WHENEVER SQLERROR CONTINUE ROLLBACK

DECLARE

BEGIN

	BEGIN
		DELETE FROM  ESB_SERVICE WHERE ID = (SELECT ID FROM ESB_SERVICE WHERE CODE = '100' AND NAME = 'Consumer' AND RCD_STATUS = '1');
	END;
	
END;
/

COMMIT;