SET ECHO ON
SET DEFINE OFF
SET SERVEROUTPUT ON
WHENEVER SQLERROR CONTINUE ROLLBACK

DECLARE

BEGIN

	BEGIN
		DELETE FROM  ESB_SYSTEM_API WHERE ID = (SELECT ID FROM ESB_SYSTEM_API WHERE SYSTEM_ID = ( SELECT ID FROM ESB_SYSTEM WHERE CODE = 'CHL-SALESFORCE') AND CODE = 'CHL-SALESFORCE-CRM' AND NAME = 'Customer Reliabilty Management' AND RCD_STATUS = '1');
	END;
	
	BEGIN
		DELETE FROM  ESB_SYSTEM_API WHERE ID = (SELECT ID FROM ESB_SYSTEM_API WHERE SYSTEM_ID = ( SELECT ID FROM ESB_SYSTEM WHERE CODE = 'FRW') AND CODE = 'FRW' AND NAME = 'Framework' AND RCD_STATUS = '1');
	END;
	
	BEGIN
		DELETE FROM  ESB_SYSTEM_API WHERE ID = (SELECT ID FROM ESB_SYSTEM_API WHERE SYSTEM_ID = ( SELECT ID FROM ESB_SYSTEM WHERE CODE = 'INT-AS400') AND CODE = 'INT-AS400-CLI' AND NAME = 'Client Management' AND RCD_STATUS = '1');
	END;
	
END;
/

COMMIT;