SET ECHO ON
SET DEFINE OFF
SET SERVEROUTPUT ON
WHENEVER SQLERROR CONTINUE ROLLBACK

DECLARE

BEGIN

	BEGIN
		DELETE FROM  ESB_SYSTEM_API_OPERATION WHERE ID = (SELECT ID FROM ESB_SYSTEM_API_OPERATION WHERE SYSTEM_API_ID = ( SELECT ID FROM ESB_SYSTEM_API WHERE CODE = 'CHL-SALESFORCE-CRM') AND VERSION = '1.0' AND NAME = 'ClientDelete' AND DESCRIPTION = 'Borra a un Cliente' AND RCD_STATUS ='1');
	END;
	
	BEGIN
		DELETE FROM  ESB_SYSTEM_API_OPERATION WHERE ID = (SELECT ID FROM ESB_SYSTEM_API_OPERATION WHERE SYSTEM_API_ID = ( SELECT ID FROM ESB_SYSTEM_API WHERE CODE = 'CHL-SALESFORCE-CRM') AND VERSION = '1.0' AND NAME = 'ClientObtain' AND DESCRIPTION = 'Obtiene un cliente' AND RCD_STATUS ='1'); 
	END;
	
	BEGIN
		DELETE FROM  ESB_SYSTEM_API_OPERATION WHERE ID = (SELECT ID FROM ESB_SYSTEM_API_OPERATION WHERE SYSTEM_API_ID = ( SELECT ID FROM ESB_SYSTEM_API WHERE CODE = 'CHL-SALESFORCE-CRM') AND VERSION = '1.0' AND NAME = 'UPD-CLI-DATA' AND DESCRIPTION = 'Actualiza la Data del Cliente' AND RCD_STATUS ='1');
	END;
	
	BEGIN
		DELETE FROM  ESB_SYSTEM_API_OPERATION WHERE ID = (SELECT ID FROM ESB_SYSTEM_API_OPERATION WHERE SYSTEM_API_ID = ( SELECT ID FROM ESB_SYSTEM_API WHERE CODE = 'INT-AS400-CLI') AND VERSION = '1.0' AND NAME = 'ClientDelete' AND DESCRIPTION = 'Borra un Cliente' AND RCD_STATUS ='1');
	END;
	
END;
/

COMMIT;