SET ECHO ON
SET DEFINE OFF
SET SERVEROUTPUT ON
WHENEVER SQLERROR CONTINUE ROLLBACK

DECLARE

BEGIN

	BEGIN
		DELETE FROM  ESB_ERROR_MAPPING WHERE ID = (SELECT ID FROM ESB_ERROR_MAPPING WHERE ERROR_SOURCE = ( SELECT ID FROM ESB_SYSTEM WHERE CODE = 'SALESFORCE') AND MODULE = 'CHL-SALESFORCE-CRM' AND SUB_MODULE = 'ClientObtain' AND RAW_CODE = '1' AND RAW_DESCRIPTION = 'Transaccion Fuera de Horario' AND CAN_ERR_ID = ( SELECT ID FROM ESB_CANONICAL_ERROR WHERE CODE = '161') AND STATUS_ID = ( SELECT ID FROM ESB_ERROR_STATUS_TYPE WHERE NAME = 'ERROR') AND RCD_STATUS='1');
	END;
	
	BEGIN
		DELETE FROM  ESB_ERROR_MAPPING WHERE ID = (SELECT ID FROM ESB_ERROR_MAPPING WHERE ERROR_SOURCE = ( SELECT ID FROM ESB_SYSTEM WHERE CODE = 'SALESFORCE') AND MODULE = 'CHL-SALESFORCE-CRM' AND SUB_MODULE = 'UPD_CLI_DATA' AND RAW_CODE = '1' AND RAW_DESCRIPTION = 'ConsumerID no encontrado' AND CAN_ERR_ID = ( SELECT ID FROM ESB_CANONICAL_ERROR WHERE CODE = '90000') AND STATUS_ID = ( SELECT ID FROM ESB_ERROR_STATUS_TYPE WHERE NAME = 'ERROR') AND RCD_STATUS='1');
	END;
	
	BEGIN
		DELETE FROM  ESB_ERROR_MAPPING WHERE ID = (SELECT ID FROM ESB_ERROR_MAPPING WHERE ERROR_SOURCE = ( SELECT ID FROM ESB_SYSTEM WHERE CODE = 'SALESFORCE') AND MODULE = 'CHL-SALESFORCE-CRM' AND SUB_MODULE = 'ClientDelete' AND RAW_CODE = '1' AND RAW_DESCRIPTION = 'Transaccion Fuera de Horario' AND CAN_ERR_ID = ( SELECT ID FROM ESB_CANONICAL_ERROR WHERE CODE = '161') AND STATUS_ID = ( SELECT ID FROM ESB_ERROR_STATUS_TYPE WHERE NAME = 'ERROR') AND RCD_STATUS ='1');
	END;
	
	BEGIN
		DELETE FROM  ESB_ERROR_MAPPING WHERE ID = (SELECT ID FROM ESB_ERROR_MAPPING WHERE ERROR_SOURCE = ( SELECT ID FROM ESB_SYSTEM WHERE CODE = 'INT-AS400') AND MODULE = 'INT-AS400-CLI' AND SUB_MODULE = 'ClientDelete' AND RAW_CODE = '1' AND RAW_DESCRIPTION = 'Cliente Inexistente' AND CAN_ERR_ID = ( SELECT ID FROM ESB_CANONICAL_ERROR WHERE CODE = '90000') AND STATUS_ID = ( SELECT ID FROM ESB_ERROR_STATUS_TYPE WHERE NAME = 'ERROR') AND RCD_STATUS='1');
	END;
	
	BEGIN
		DELETE FROM  ESB_ERROR_MAPPING WHERE ID = (SELECT ID FROM ESB_ERROR_MAPPING WHERE ERROR_SOURCE = ( SELECT ID FROM ESB_SYSTEM WHERE CODE = 'CHL-SALESFORCE') AND MODULE IS NULL AND SUB_MODULE IS NULL AND RAW_CODE IS NULL AND RAW_DESCRIPTION IS NULL AND CAN_ERR_ID = ( SELECT ID FROM ESB_CANONICAL_ERROR WHERE CODE = '350') AND STATUS_ID = ( SELECT ID FROM ESB_ERROR_STATUS_TYPE WHERE NAME = 'ERROR') AND RCD_STATUS='1');
	END;
	
	BEGIN
		DELETE FROM  ESB_ERROR_MAPPING WHERE ID = (SELECT ID FROM ESB_ERROR_MAPPING WHERE ERROR_SOURCE = ( SELECT ID FROM ESB_SYSTEM WHERE CODE = 'INT-AS400') AND MODULE IS NULL AND SUB_MODULE IS NULL AND RAW_CODE IS NULL AND RAW_DESCRIPTION IS NULL AND CAN_ERR_ID = ( SELECT ID FROM ESB_CANONICAL_ERROR WHERE CODE = '351') AND STATUS_ID = ( SELECT ID FROM ESB_ERROR_STATUS_TYPE WHERE NAME = 'ERROR') AND RCD_STATUS='1');
	END;
	
	BEGIN
		DELETE FROM  ESB_ERROR_MAPPING WHERE ID = (SELECT ID FROM ESB_ERROR_MAPPING WHERE ERROR_SOURCE = ( SELECT ID FROM ESB_SYSTEM WHERE CODE = 'CHL-SALESFORCE') AND RAW_CODE = '0'  AND CAN_ERR_ID = ( SELECT ID FROM ESB_CANONICAL_ERROR WHERE CODE = '0') AND STATUS_ID = ( SELECT ID FROM ESB_ERROR_STATUS_TYPE WHERE NAME = 'OK') AND RCD_STATUS='1');
	END;
	
	BEGIN
		DELETE FROM  ESB_ERROR_MAPPING WHERE ID = (SELECT ID FROM ESB_ERROR_MAPPING WHERE ERROR_SOURCE = ( SELECT ID FROM ESB_SYSTEM WHERE CODE = 'INT-AS400') AND RAW_CODE = '0'  AND CAN_ERR_ID = ( SELECT ID FROM ESB_CANONICAL_ERROR WHERE CODE = '0') AND STATUS_ID = ( SELECT ID FROM ESB_ERROR_STATUS_TYPE WHERE NAME = 'OK') AND RCD_STATUS='1');
	END;
	
END;
/

COMMIT;