SET ECHO ON
SET DEFINE OFF
SET SERVEROUTPUT ON
WHENEVER SQLERROR CONTINUE ROLLBACK

DECLARE

BEGIN

	BEGIN
		DELETE FROM  ESB_ERROR_DIAGNOSIS WHERE ID = (SELECT ID FROM ESB_ERROR_DIAGNOSIS WHERE CAPABILITY_ID = ( SELECT ID FROM ESB_CAPABILITY WHERE CODE = '101') AND F_CODE = '1' AND T_CODE = '50' AND TYPE = '2' AND WEIGHT = '3' AND THERAPY_ID = ( SELECT ID FROM ESB_ERROR_THERAPY WHERE NAME = 'SALESFORCE') AND RCD_STATUS = '1');
	END;
	
	BEGIN
		DELETE FROM  ESB_ERROR_DIAGNOSIS WHERE ID = (SELECT ID FROM ESB_ERROR_DIAGNOSIS WHERE CAPABILITY_ID = ( SELECT ID FROM ESB_CAPABILITY WHERE CODE = '101') AND F_CODE = '*' AND T_CODE = '*' AND TYPE = '*' AND WEIGHT = '1' AND THERAPY_ID = ( SELECT ID FROM ESB_ERROR_THERAPY WHERE NAME = 'SALESFORCE') AND RCD_STATUS = '1');
	END;
	
	BEGIN
		DELETE FROM  ESB_ERROR_DIAGNOSIS WHERE ID = (SELECT ID FROM ESB_ERROR_DIAGNOSIS WHERE CAPABILITY_ID = ( SELECT ID FROM ESB_CAPABILITY WHERE CODE = '103') AND F_CODE = '*' AND T_CODE = '*' AND TYPE = '*' AND WEIGHT = '1' AND THERAPY_ID = ( SELECT ID FROM ESB_ERROR_THERAPY WHERE NAME = 'SALESFORCE') AND RCD_STATUS = '1'); 
	END;
	
	BEGIN
		DELETE FROM  ESB_ERROR_DIAGNOSIS WHERE ID = (SELECT ID FROM ESB_ERROR_DIAGNOSIS WHERE CAPABILITY_ID = ( SELECT ID FROM ESB_CAPABILITY WHERE CODE = '104') AND F_CODE = '*' AND T_CODE = '*' AND TYPE = '*' AND WEIGHT = '1' AND THERAPY_ID = ( SELECT ID FROM ESB_ERROR_THERAPY WHERE NAME = 'SALESFORCE') AND RCD_STATUS = '1'); 
	END;
	
	BEGIN
    	DELETE FROM  ESB_ERROR_DIAGNOSIS WHERE CAPABILITY_ID = (SELECT ID FROM ESB_CAPABILITY WHERE CODE = '101') AND THERAPY_ID = ( SELECT ID FROM ESB_ERROR_THERAPY WHERE NAME = 'TERAPIA_1');
	END;	
		
END;
/

COMMIT;