SET ECHO ON
SET DEFINE OFF
SET SERVEROUTPUT ON
WHENEVER SQLERROR CONTINUE ROLLBACK

DECLARE

BEGIN

	BEGIN
		DELETE FROM  ESB_CONSUMER_DETAILS WHERE ID = (SELECT ID FROM ESB_CONSUMER_DETAILS WHERE CONSUMER_ID = ( SELECT ID FROM ESB_CONSUMER WHERE SYSCODE = ( SELECT ID FROM ESB_SYSTEM WHERE CODE = 'SALESFORCE') AND COUNTRY_ID = ( SELECT ID FROM ESB_COUNTRY WHERE CODE = 'CHL') AND ENT_CODE = ( SELECT ID FROM ESB_ENTERPRISE WHERE CODE = 'ENTEL')) AND DETAIL_TYPE_ID = ( SELECT ID FROM ESB_CONSUMER_DETAILS_TYPE WHERE NAME = 'URL') AND to_char(DETAIL_CONTENT) = 'HTTP://172.17.201.86:7003/Dummmy_GetConsumerCallback');
	END;
	
	BEGIN
		DELETE FROM  ESB_CONSUMER_DETAILS WHERE ID = (SELECT ID FROM ESB_CONSUMER_DETAILS WHERE CONSUMER_ID = ( SELECT ID FROM ESB_CONSUMER WHERE SYSCODE = ( SELECT ID FROM ESB_SYSTEM WHERE CODE = 'SALESFORCE') AND COUNTRY_ID = ( SELECT ID FROM ESB_COUNTRY WHERE CODE = 'CHL') AND ENT_CODE = ( SELECT ID FROM ESB_ENTERPRISE WHERE CODE = 'ENTEL')) AND DETAIL_TYPE_ID = ( SELECT ID FROM ESB_CONSUMER_DETAILS_TYPE WHERE NAME = 'TRANSPORT') AND to_char(DETAIL_CONTENT) = 'HTTP');
	END;
	
	BEGIN
		DELETE FROM  ESB_CONSUMER_DETAILS WHERE ID = (SELECT ID FROM ESB_CONSUMER_DETAILS WHERE CONSUMER_ID = ( SELECT ID FROM ESB_CONSUMER WHERE SYSCODE = ( SELECT ID FROM ESB_SYSTEM WHERE CODE = 'SALESFORCE') AND COUNTRY_ID = ( SELECT ID FROM ESB_COUNTRY WHERE CODE = 'CHL') AND ENT_CODE = ( SELECT ID FROM ESB_ENTERPRISE WHERE CODE = 'ENTEL')) AND DETAIL_TYPE_ID = ( SELECT ID FROM ESB_CONSUMER_DETAILS_TYPE WHERE NAME = 'Mail') AND to_char(DETAIL_CONTENT) = 'facundoferro@gmail.com');
	END;
	
	BEGIN
		DELETE FROM  ESB_CONSUMER_DETAILS WHERE ID = (SELECT ID FROM ESB_CONSUMER_DETAILS WHERE CONSUMER_ID = ( SELECT ID FROM ESB_CONSUMER WHERE SYSCODE = ( SELECT ID FROM ESB_SYSTEM WHERE CODE = 'SALESFORCE') AND COUNTRY_ID = ( SELECT ID FROM ESB_COUNTRY WHERE CODE = 'CHL') AND ENT_CODE = ( SELECT ID FROM ESB_ENTERPRISE WHERE CODE = 'ENTEL')) AND DETAIL_TYPE_ID = ( SELECT ID FROM ESB_CONSUMER_DETAILS_TYPE WHERE NAME = 'Mail') AND to_char(DETAIL_CONTENT) = 'gemny.ibarra@globallogic.com');
	END;
	
	BEGIN
		DELETE FROM  ESB_CONSUMER_DETAILS WHERE ID = (SELECT ID FROM ESB_CONSUMER_DETAILS WHERE CONSUMER_ID = ( SELECT ID FROM ESB_CONSUMER WHERE SYSCODE = ( SELECT ID FROM ESB_SYSTEM WHERE CODE = 'SALESFORCE') AND COUNTRY_ID = ( SELECT ID FROM ESB_COUNTRY WHERE CODE = 'CHL') AND ENT_CODE = ( SELECT ID FROM ESB_ENTERPRISE WHERE CODE = 'ENTEL')) AND DETAIL_TYPE_ID = ( SELECT ID FROM ESB_CONSUMER_DETAILS_TYPE WHERE NAME = 'Mail') AND to_char(DETAIL_CONTENT) = 'sole.alfonso@globallogic.com');
	END;
	
	BEGIN
		DELETE FROM  ESB_CONSUMER_DETAILS WHERE ID = (SELECT ID FROM ESB_CONSUMER_DETAILS WHERE CONSUMER_ID = ( SELECT ID FROM ESB_CONSUMER WHERE SYSCODE = ( SELECT ID FROM ESB_SYSTEM WHERE CODE = 'SALESFORCE') AND COUNTRY_ID = ( SELECT ID FROM ESB_COUNTRY WHERE CODE = 'CHL') AND ENT_CODE = ( SELECT ID FROM ESB_ENTERPRISE WHERE CODE = 'ENTEL')) AND DETAIL_TYPE_ID = ( SELECT ID FROM ESB_CONSUMER_DETAILS_TYPE WHERE NAME = 'Mail') AND to_char(DETAIL_CONTENT) = 'mario.mesaglio@globallogic.com');
	END;
	
	BEGIN
		DELETE FROM  ESB_CONSUMER_DETAILS WHERE ID = (SELECT ID FROM ESB_CONSUMER_DETAILS WHERE CONSUMER_ID = ( SELECT ID FROM ESB_CONSUMER WHERE SYSCODE = ( SELECT ID FROM ESB_SYSTEM WHERE CODE = 'SALESFORCE') AND COUNTRY_ID = ( SELECT ID FROM ESB_COUNTRY WHERE CODE = 'CHL') AND ENT_CODE = ( SELECT ID FROM ESB_ENTERPRISE WHERE CODE = 'ENTEL')) AND DETAIL_TYPE_ID = ( SELECT ID FROM ESB_CONSUMER_DETAILS_TYPE WHERE NAME = 'Mail') AND to_char(DETAIL_CONTENT) = 'matias.gonsalves@globallogic.com');
	END;
END;
/

COMMIT;