SET ECHO ON
SET DEFINE OFF
SET SERVEROUTPUT ON
WHENEVER SQLERROR CONTINUE ROLLBACK

DECLARE

BEGIN

	BEGIN
		DELETE FROM  ESB_CHECK_CONFIG WHERE CAP_CHK_ID = (SELECT ID FROM ESB_CAPABILITY_CHECK WHERE CAPABILITY_ID = ( SELECT ID FROM ESB_CAPABILITY WHERE CODE = '103')) AND CHECK_TYPE_ID = ( SELECT ID FROM ESB_CHECK_TYPE WHERE NAME = 'IDEMPOTENT') AND ELAPSED_TIME = '0 0:1:0.0' AND RCD_STATUS = '1';
	END;
	
	BEGIN
		DELETE FROM  ESB_CHECK_CONFIG WHERE CAP_CHK_ID = (SELECT ID FROM ESB_CAPABILITY_CHECK WHERE CAPABILITY_ID = ( SELECT ID FROM ESB_CAPABILITY WHERE CODE = '103')) AND CHECK_TYPE_ID = ( SELECT ID FROM ESB_CHECK_TYPE WHERE NAME = 'RESULT') AND ELAPSED_TIME = '0 0:1:30.0' AND RCD_STATUS = '1';
	END;
	
END;
/

COMMIT;