SET ECHO ON
SET DEFINE OFF
SET SERVEROUTPUT ON
WHENEVER SQLERROR CONTINUE ROLLBACK

DECLARE

BEGIN

	BEGIN
		DELETE FROM  ESB_CHANNEL WHERE ID = (SELECT ID FROM ESB_CHANNEL WHERE CODE = '99' AND NAME = 'WEB' AND RCD_STATUS = '0');
	END;
	
END;
/

COMMIT;