SET ECHO ON
SET DEFINE OFF
SET SERVEROUTPUT ON
WHENEVER SQLERROR CONTINUE ROLLBACK

DECLARE

BEGIN

	BEGIN
		DELETE FROM  ESB_CAPABILITY_CHECK WHERE ID = (SELECT ID FROM ESB_CAPABILITY_CHECK WHERE CAPABILITY_ID = ( SELECT ID FROM ESB_CAPABILITY WHERE CODE = '103') AND CHECK_INDICATOR = '1' AND RCD_STATUS = '1');
	END;
	
	BEGIN
		DELETE FROM  ESB_CAPABILITY_CHECK WHERE ID = (SELECT ID FROM ESB_CAPABILITY_CHECK WHERE CAPABILITY_ID = ( SELECT ID FROM ESB_CAPABILITY WHERE CODE = '104') AND CHECK_INDICATOR = '0' AND RCD_STATUS = '1');
	END;
	
	BEGIN
		DELETE FROM  ESB_CAPABILITY_CHECK WHERE ID = (SELECT ID FROM ESB_CAPABILITY_CHECK WHERE CAPABILITY_ID = ( SELECT ID FROM ESB_CAPABILITY WHERE CODE = '101') AND CHECK_INDICATOR = '0' AND RCD_STATUS = '1');
	END;
	
	BEGIN
		DELETE FROM  ESB_CAPABILITY_CHECK WHERE ID = (SELECT ID FROM ESB_CAPABILITY_CHECK WHERE CAPABILITY_ID = ( SELECT ID FROM ESB_CAPABILITY WHERE CODE = '102') AND CHECK_INDICATOR = '0' AND RCD_STATUS = '1');
	END;
	
END;
/

COMMIT;