SET ECHO ON
SET DEFINE OFF
SET SERVEROUTPUT ON
WHENEVER SQLERROR CONTINUE ROLLBACK

DECLARE

BEGIN

	BEGIN
		DELETE FROM  ESB_CONSUMER WHERE ID = (SELECT ID FROM ESB_CONSUMER WHERE SYSCODE = ( SELECT ID FROM ESB_SYSTEM WHERE CODE = 'CHL-SALESFORCE') AND COUNTRY_ID = ( SELECT ID FROM ESB_COUNTRY WHERE CODE = 'CHL') AND ENT_CODE = ( SELECT ID FROM ESB_ENTERPRISE WHERE CODE = 'ENTEL') AND RCD_STATUS = '0');
	END;
	BEGIN
		DELETE FROM ESB_CONSUMER WHERE SYSCODE = ( SELECT ID FROM ESB_SYSTEM WHERE CODE = 'CR0002') AND COUNTRY_ID = ( SELECT ID FROM ESB_COUNTRY WHERE CODE = 'CHL') AND ENT_CODE = ( SELECT ID FROM ESB_ENTERPRISE WHERE CODE = 'ENTEL') AND RCD_STATUS = '1';
	END;
END;
/

COMMIT;