<wsdl:definitions
     name="ESB_RETRYMANAGER_Pooling"
     targetNamespace="http://xmlns.oracle.com/pcbpel/adapter/db/DC_SC_ErrorManager/RetryTreatment_Admission/ESB_RETRYMANAGER_Pooling"
     xmlns:tns="http://xmlns.oracle.com/pcbpel/adapter/db/DC_SC_ErrorManager/RetryTreatment_Admission/ESB_RETRYMANAGER_Pooling"
     xmlns:jca="http://xmlns.oracle.com/pcbpel/wsdl/jca/"
     xmlns:plt="http://schemas.xmlsoap.org/ws/2003/05/partner-link/"
     xmlns:pc="http://xmlns.oracle.com/pcbpel/"
     xmlns:top="http://xmlns.oracle.com/pcbpel/adapter/db/top/ESB_RETRYMANAGER_Pooling"
     xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/"
     xmlns:ns1="http://xmlns.oracle.com/pcbpel/adapter/db/sp/RETRY_UPDATE_STATUS"
    >
  <plt:partnerLinkType name="ESB_RETRYMANAGER_Pooling_plt" >
    <plt:role name="ESB_RETRYMANAGER_Pooling_role" >
      <plt:portType name="tns:ESB_RETRYMANAGER_Pooling_ptt" />
    </plt:role>
  </plt:partnerLinkType>
  <plt:partnerLinkType name="ESB_RETRYMANAGER_Pooling_plt" >
    <plt:role name="ESB_RETRYMANAGER_Pooling_role" >
      <plt:portType name="tns:ESB_RETRYMANAGER_Pooling_ptt" />
    </plt:role>
  </plt:partnerLinkType>
  <plt:partnerLinkType name="ESB_RETRYMANAGER_Pooling_plt" >
    <plt:role name="ESB_RETRYMANAGER_Pooling_role" >
      <plt:portType name="tns:ESB_RETRYMANAGER_Pooling_ptt" />
    </plt:role>
  </plt:partnerLinkType>
  <plt:partnerLinkType name="ESB_RETRYMANAGER_Pooling_plt" >
    <plt:role name="ESB_RETRYMANAGER_Pooling_role" >
      <plt:portType name="tns:ESB_RETRYMANAGER_Pooling_ptt" />
    </plt:role>
  </plt:partnerLinkType>
  <plt:partnerLinkType name="ESB_RETRYMANAGER_Pooling_plt" >
    <plt:role name="ESB_RETRYMANAGER_Pooling_role" >
      <plt:portType name="tns:ESB_RETRYMANAGER_Pooling_ptt" />
    </plt:role>
  </plt:partnerLinkType>
  <plt:partnerLinkType name="ESB_RETRYMANAGER_Pooling_plt" >
    <plt:role name="ESB_RETRYMANAGER_Pooling_role" >
      <plt:portType name="tns:ESB_RETRYMANAGER_Pooling_ptt" />
    </plt:role>
  </plt:partnerLinkType>
  <plt:partnerLinkType name="ESB_RETRYMANAGER_Pooling_plt" >
    <plt:role name="ESB_RETRYMANAGER_Pooling_role" >
      <plt:portType name="tns:ESB_RETRYMANAGER_Pooling_ptt" />
    </plt:role>
  </plt:partnerLinkType>
    <wsdl:types>
      <schema xmlns="http://www.w3.org/2001/XMLSchema" >
        <import namespace="http://xmlns.oracle.com/pcbpel/adapter/db/top/ESB_RETRYMANAGER_Pooling" schemaLocation="../Schemas/ESB_RETRYMANAGER_Pooling_table.xsd" />
      </schema>
      <schema xmlns="http://www.w3.org/2001/XMLSchema" >
        <import namespace="http://xmlns.oracle.com/pcbpel/adapter/db/sp/RETRY_UPDATE_STATUS" schemaLocation="../Schemas/RETRY_UPDATE_STATUS_sp.xsd" />
      </schema>
    </wsdl:types>
    <wsdl:message name="EsbRetrymanagerCollection_msg">
        <wsdl:part name="EsbRetrymanagerCollection" element="top:EsbRetrymanagerCollection"/>
    </wsdl:message>
    <wsdl:portType name="ESB_RETRYMANAGER_Pooling_ptt">
        <wsdl:operation name="receive">
            <wsdl:input message="tns:EsbRetrymanagerCollection_msg"/>
        </wsdl:operation>
    </wsdl:portType>
</wsdl:definitions>
