<?xml version= '1.0' encoding= 'UTF-8' ?>
<wsdl:definitions
     name="ErrorManager"
     targetNamespace="http://www.entel.cl/SC/ErrorManager/v1"
     xmlns:xsd="http://www.w3.org/2001/XMLSchema"
     xmlns:bpws="http://docs.oasis-open.org/wsbpel/2.0/process/executable"
     xmlns:plnk="http://docs.oasis-open.org/wsbpel/2.0/plnktype"
     xmlns:WL5G3N3="http://www.entel.cl/SC/ErrorManager/v1"
     xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/"
    >
    <plnk:partnerLinkType name="DReference_ErrorManager">
        <plnk:role name="ErrorManager_PortType" portType="WL5G3N3:ErrorManager_PortType"/>
    </plnk:partnerLinkType>
    <wsdl:import namespace="http://www.entel.cl/SC/ErrorManager/v1" location="oramds:/apps/Commons/DC_SC_ErrorManager/SupportAPI/WSDL/ErrorManager.wsdl"/>
</wsdl:definitions>
