<?xml version= '1.0' encoding= 'UTF-8' ?>
<wsdl:definitions
     name="Update_Consumer_OH_BPELProcess"
     targetNamespace="http://xmlns.oracle.com/ES_Consumer_v1/Update_Consumer_OH/Update_Consumer_OH_BPELProcess"
     xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/"
     xmlns:client="http://xmlns.oracle.com/ES_Consumer_v1/Update_Consumer_OH/Update_Consumer_OH_BPELProcess"
     xmlns:ns1="http://www.entel.cl/EBM/Consumer/upd/v1"
     xmlns:plnk="http://docs.oasis-open.org/wsbpel/2.0/plnktype"
     xmlns:cor="http://xmlns.oracle.com/ES_Consumer_v1/Update_Consumer_OH/Update_Consumer_OH_BPELProcess/correlationset"
     xmlns:bpel="http://docs.oasis-open.org/wsbpel/2.0/process/executable"
     xmlns:vprop="http://docs.oasis-open.org/wsbpel/2.0/varprop"
     xmlns:ns="http://xmlns.oracle.com/pcbpel/adapter/jms/ES_Consumer_v1/Update_Consumer_OH/jmsReference_Upd_RA_SALESFORCE"
     xmlns:ns2="http://schemas.oracle.com/bpel/extension"
     xmlns:ns3="http://www.entel.cl/ESO/MessageHeader/v1"
     xmlns:ns4="http://www.entel.cl/ESO/Result/v2"
    >
    <plnk:partnerLinkType name="Update_Consumer_OH_BPELProcess">
        <plnk:role name="Update_Consumer_OH_BPELProcessProvider" portType="client:Update_Consumer_OH_BPELProcess"/>
    </plnk:partnerLinkType>
    <vprop:propertyAlias propertyName="cor:conversationId" xmlns:client="http://xmlns.oracle.com/ES_Consumer_v1/Update_Consumer_OH/Update_Consumer_OH_BPELProcess"
         messageType="client:Update_Consumer_OH_BPELProcessRequestMessage" part="payload"
         xmlns:ns2="http://www.entel.cl/ESO/MessageHeader/v1">
        <vprop:query>ns2:RequestHeader/ns2:Trace/@conversationID</vprop:query>
    </vprop:propertyAlias>
    <vprop:propertyAlias propertyName="cor:conversationId" xmlns:ns19="http://xmlns.oracle.com/pcbpel/adapter/jms/ES_Consumer_v1/Update_Consumer_OH/jmsReference_Upd_RA_SALESFORCE"
         messageType="ns19:Reply_msg_in" part="CHL-SALESFORCE-CRM_UPD-CLI-DATA_RSP" xmlns:ns3="http://www.entel.cl/ESO/MessageHeader/v1">
        <vprop:query>ns3:RequestHeader/ns3:Trace/@conversationID</vprop:query>
    </vprop:propertyAlias>
    <wsdl:import namespace="http://xmlns.oracle.com/pcbpel/adapter/jms/ES_Consumer_v1/Update_Consumer_OH/jmsReference_Upd_RA_SALESFORCE"
         location="jmsReference_Upd_RA_SALESFORCE.wsdl"/>
    <wsdl:import namespace="http://xmlns.oracle.com/ES_Consumer_v1/Update_Consumer_OH/Update_Consumer_OH_BPELProcess/correlationset"
         location="Update_Consumer_OH_BPELProcess_properties.wsdl"/>
    <wsdl:import namespace="http://schemas.oracle.com/bpel/extension" location="RuntimeFault.wsdl"/>
    <wsdl:types>
        <schema xmlns="http://www.w3.org/2001/XMLSchema" xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/"
             xmlns:client="http://xmlns.oracle.com/ES_Consumer_v1/Update_Consumer_OH/Update_Consumer_OH_BPELProcess"
             xmlns:ns1="http://www.entel.cl/EBM/Consumer/upd/v1" xmlns:plnk="http://docs.oasis-open.org/wsbpel/2.0/plnktype"
             xmlns:cor="http://xmlns.oracle.com/ES_Consumer_v1/Update_Consumer_OH/Update_Consumer_OH_BPELProcess/correlationset"
             xmlns:bpel="http://docs.oasis-open.org/wsbpel/2.0/process/executable" xmlns:vprop="http://docs.oasis-open.org/wsbpel/2.0/varprop"
             xmlns:ns="http://xmlns.oracle.com/pcbpel/adapter/jms/ES_Consumer_v1/Update_Consumer_OH/jmsReference_Upd_RA_SALESFORCE"
             xmlns:ns2="http://schemas.oracle.com/bpel/extension" xmlns:ns3="http://www.entel.cl/ESO/MessageHeader/v1"
             xmlns:ns4="http://www.entel.cl/ESO/Result/v2">
            <import namespace="http://www.entel.cl/EBM/Consumer/upd/v1" schemaLocation="oramds:/apps/Commons/ES_Consumer_v1/ESC/Primary/upd_Consumer_v1_EBM.xsd"/>
        </schema>
        <xsd:schema xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/"
             xmlns:client="http://xmlns.oracle.com/ES_Consumer_v1/Update_Consumer_OH/Update_Consumer_OH_BPELProcess"
             xmlns:ns1="http://www.entel.cl/EBM/Consumer/upd/v1" xmlns:plnk="http://docs.oasis-open.org/wsbpel/2.0/plnktype"
             xmlns:cor="http://xmlns.oracle.com/ES_Consumer_v1/Update_Consumer_OH/Update_Consumer_OH_BPELProcess/correlationset"
             xmlns:bpel="http://docs.oasis-open.org/wsbpel/2.0/process/executable" xmlns:vprop="http://docs.oasis-open.org/wsbpel/2.0/varprop"
             xmlns:ns="http://xmlns.oracle.com/pcbpel/adapter/jms/ES_Consumer_v1/Update_Consumer_OH/jmsReference_Upd_RA_SALESFORCE"
             xmlns:ns2="http://schemas.oracle.com/bpel/extension" xmlns:ns3="http://www.entel.cl/ESO/MessageHeader/v1"
             xmlns:ns4="http://www.entel.cl/ESO/Result/v2">
            <xsd:import namespace="http://www.entel.cl/ESO/MessageHeader/v1" schemaLocation="oramds:/apps/Commons/SR_Commons/XSD/ESO/MessageHeader_v1_ESO.xsd"/>
        </xsd:schema>
        <xsd:schema xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/"
             xmlns:client="http://xmlns.oracle.com/ES_Consumer_v1/Update_Consumer_OH/Update_Consumer_OH_BPELProcess"
             xmlns:ns1="http://www.entel.cl/EBM/Consumer/upd/v1" xmlns:plnk="http://docs.oasis-open.org/wsbpel/2.0/plnktype"
             xmlns:cor="http://xmlns.oracle.com/ES_Consumer_v1/Update_Consumer_OH/Update_Consumer_OH_BPELProcess/correlationset"
             xmlns:bpel="http://docs.oasis-open.org/wsbpel/2.0/process/executable" xmlns:vprop="http://docs.oasis-open.org/wsbpel/2.0/varprop"
             xmlns:ns="http://xmlns.oracle.com/pcbpel/adapter/jms/ES_Consumer_v1/Update_Consumer_OH/jmsReference_Upd_RA_SALESFORCE"
             xmlns:ns2="http://schemas.oracle.com/bpel/extension" xmlns:ns3="http://www.entel.cl/ESO/MessageHeader/v1"
             xmlns:ns4="http://www.entel.cl/ESO/Result/v2">
            <xsd:import namespace="http://www.entel.cl/ESO/Result/v2" schemaLocation="oramds:/apps/Commons/SR_Commons/XSD/ESO/Result_v2_ESO.xsd"/>
        </xsd:schema>
    </wsdl:types>
    <wsdl:message name="Update_Consumer_OH_BPELProcessRequestMessage">
        <wsdl:part name="payload" element="ns1:Upd_Consumer_REQ"/>
    </wsdl:message>
    <wsdl:message name="Update_Consumer_OH_BPELProcessResponseMessage">
        <wsdl:part name="payload" element="ns1:Upd_Consumer_RSP"/>
    </wsdl:message>
    <wsdl:message name="Update_Consumer_OH_BPELProcessFaultMessage">
        <wsdl:part name="FAULT_part" element="ns1:Upd_Consumer_FRSP"/>
    </wsdl:message>
    <wsdl:portType name="Update_Consumer_OH_BPELProcess">
        <wsdl:operation name="process">
            <wsdl:input message="client:Update_Consumer_OH_BPELProcessRequestMessage"/>
            <wsdl:output message="client:Update_Consumer_OH_BPELProcessResponseMessage"/>
            <wsdl:fault name="processFault" message="client:Update_Consumer_OH_BPELProcessFaultMessage"/>
        </wsdl:operation>
    </wsdl:portType>
</wsdl:definitions>
