<wsdl:definitions
     name="ESB_ERROR_DERIVATION_CONFIG_Polling"
     targetNamespace="http://xmlns.oracle.com/pcbpel/adapter/db/DC_SC_ErrorManager/ErrorDerivation/ESB_ERROR_DERIVATION_CONFIG_Polling"
     xmlns:tns="http://xmlns.oracle.com/pcbpel/adapter/db/DC_SC_ErrorManager/ErrorDerivation/ESB_ERROR_DERIVATION_CONFIG_Polling"
     xmlns:jca="http://xmlns.oracle.com/pcbpel/wsdl/jca/"
     xmlns:plt="http://schemas.xmlsoap.org/ws/2003/05/partner-link/"
     xmlns:pc="http://xmlns.oracle.com/pcbpel/"
     xmlns:top="http://xmlns.oracle.com/pcbpel/adapter/db/top/ESB_ERROR_DERIVATION_CONFIG_Polling"
     xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/"
    >
  <plt:partnerLinkType name="ESB_ERROR_DERIVATION_CONFIG_Polling_plt" >
    <plt:role name="ESB_ERROR_DERIVATION_CONFIG_Polling_role" >
      <plt:portType name="tns:ESB_ERROR_DERIVATION_CONFIG_Polling_ptt" />
    </plt:role>
  </plt:partnerLinkType>
    <wsdl:types>
      <schema xmlns="http://www.w3.org/2001/XMLSchema" >
        <import namespace="http://xmlns.oracle.com/pcbpel/adapter/db/top/ESB_ERROR_DERIVATION_CONFIG_Polling" schemaLocation="../Schemas/ESB_ERROR_DERIVATION_CONFIG_Polling_table.xsd" />
      </schema>
    </wsdl:types>
    <wsdl:message name="EsbErrorDerivationConfCollection_msg">
        <wsdl:part name="EsbErrorDerivationConfCollection" element="top:EsbErrorDerivationConfCollection"/>
    </wsdl:message>
    <wsdl:portType name="ESB_ERROR_DERIVATION_CONFIG_Polling_ptt">
        <wsdl:operation name="receive">
            <wsdl:input message="tns:EsbErrorDerivationConfCollection_msg"/>
        </wsdl:operation>
    </wsdl:portType>
</wsdl:definitions>
