<wsdl:definitions targetNamespace="http://www.entel.cl/RA/CHL-SALESFORCE-CRM/ClientDelete/v1" xmlns:tns="http://www.entel.cl/RA/CHL-SALESFORCE-CRM/ClientDelete/v1" xmlns:xs="http://www.w3.org/2001/XMLSchema" xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/" xmlns:wsoap12="http://schemas.xmlsoap.org/wsdl/soap12/" xmlns:ns="http://schemas.xmlsoap.org/soap/encoding/" xmlns:csmns="http://www.entel.cl/CSM/RA/CHL-SALESFORCE-CRM/ClientDelete/v1">
  <wsdl:types>
    <xs:schema xmlns:xsd="http://www.w3.org/2001/XMLSchema">
      <xs:import namespace="http://www.entel.cl/CSM/RA/CHL-SALESFORCE-CRM/ClientDelete/v1"
                 schemaLocation="CHL-SALESFORCE-CRM_ClientDelete_v1_CSM.xsd"/>
    </xs:schema>
  </wsdl:types>

  <wsdl:message name="ClientDelete_Message_In">
    <wsdl:part name="In" element="csmns:CHL-SALESFORCE-CRM_ClientDelete_REQ"/>
  </wsdl:message>
  
  <wsdl:message name="ClientDelete_Message_Out">
    <wsdl:part name="Out" element="csmns:CHL-SALESFORCE-CRM_ClientDelete_RSP"/>
  </wsdl:message>
  
 
  <wsdl:portType name="ClientDelete_PortType">
    <wsdl:operation name="ClientDelete">
      <wsdl:input message="tns:ClientDelete_Message_In"/>
      <wsdl:output message="tns:ClientDelete_Message_Out"/>
    </wsdl:operation>
  </wsdl:portType>

  
  <wsdl:binding name="ClientDelete_SOAP12Binding" type="tns:ClientDelete_PortType">
    <wsoap12:binding style="document" transport="http://www.bea.com/wli/sb/transports/sb"/>
    <wsdl:operation name="ClientDelete">
      <wsoap12:operation style="document" soapAction=""/>
      <wsdl:input>
        <wsoap12:body use="literal"/>
      </wsdl:input>
      <wsdl:output>
        <wsoap12:body use="literal"/>
      </wsdl:output>
    </wsdl:operation>
  </wsdl:binding>

  <wsdl:service name="ClientDelete_Service">
    <wsdl:port name="ClientDelete_Port" binding="tns:ClientDelete_SOAP12Binding">
      <wsoap12:address location="sb://CHL-SALESFORCE-CRM_ClientDelete_RA"/>
    </wsdl:port>
  </wsdl:service>

</wsdl:definitions>