<wsdl:definitions targetNamespace="http://xmlns.oracle.com/pcbpel/adapter/db/ENTEL_ServiceBusApp/DC_SC_ParameterManager/getConfigParameterManagerAdapter" name="getConfigParameterManagerAdapter-concrete" xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/" xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/">
    <wsdl:import location="getConfigParameterManagerAdapter.wsdl" namespace="http://xmlns.oracle.com/pcbpel/adapter/db/ENTEL_ServiceBusApp/DC_SC_ParameterManager/getConfigParameterManagerAdapter"/>
    <wsdl:binding name="getConfigParameterManagerAdapter_ptt-binding" type="get:getConfigParameterManagerAdapter_ptt" xmlns:get="http://xmlns.oracle.com/pcbpel/adapter/db/ENTEL_ServiceBusApp/DC_SC_ParameterManager/getConfigParameterManagerAdapter">
        <soap:binding style="document" transport="http://www.bea.com/wli/sb/transports/jca"/>
        <wsdl:operation name="getConfigParameterManagerAdapter">
            <soap:operation soapAction="getConfigParameterManagerAdapter"/>
            <wsdl:input>
                <soap:body use="literal"/>
            </wsdl:input>
            <wsdl:output>
                <soap:body use="literal"/>
            </wsdl:output>
        </wsdl:operation>
    </wsdl:binding>
</wsdl:definitions>